"""A verification target chosen from the profile's own gamut (#133, feature B).

The master set is ONE deterministic, versioned list of colours (issue #133
§5.1), generated by Argyll's ``targen -t`` — *Incremental Far Point
Distribution*, which picks each point as far as possible from everything
already picked, so **every prefix is itself a well-spread set** (§5.2's
nesting, by construction; verified byte-compared in the planning session).
The bundled set is marked **PROVISIONAL** (§5.4 / the plan's one irreversible
decision): it may be re-cut freely until somebody outside this project relies
on a report that names it, and only then is it frozen under a version number.

For a given profile this module *selects*: every master colour is pushed
backward through the profile (its B2A — "which ink amounts produce this
colour?") and forward again (its A2B), and the round-trip ΔE76 says whether
the profile can actually reach it. Two numbers fall out, answering two
different questions (§5.1):

* **coverage** — how many of the master set this profile can print at all;
* the **chart** — the first *n* reachable colours in master order, so a small
  chart is a genuine sample of a large one.

The eight cube corners are appended **unconditionally, outside the filter**
(§9a): they measure how far the ink and paper reach, which is a property the
profile has no say in, so the gamut filter must never remove them. They are
excluded from the accuracy statistics and reported in their own section.

The chart's ``.ti2`` ends up holding **final device values** — the profile is
applied at *build* time — so the sheet must print **raw**; the stored
colorimetric reference beside the chart is both the report's yardstick and the
marker the Print tab already reads to force Raw (feature A, §3.1a).

Process model: ``subprocess.run`` through :mod:`workflow.xicclu_runner`'s
injectable runners — never the ArgyllRunner singleton, always with a timeout.
"""
from __future__ import annotations

import json
import math
import subprocess
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Callable, Sequence

from core.logger import get_logger
from core.resource_path import resource_path

log = get_logger(__name__)

#: The published master set (PROVISIONAL — see the module docstring).
MASTER_SET_VERSION = "PROVISIONAL-r1"
MASTER_SET_ASSET = f"assets/verification/chromiq-verification-set-{MASTER_SET_VERSION}.ti1"

#: §6 — the two margin choices. "Safe" keeps targets away from the gamut
#: boundary with a tightened round-trip threshold; "full" allows everything
#: the profile can technically reach.
MARGIN_SAFE = "safe"
MARGIN_FULL = "full"
#: ΔE76 round-trip thresholds. 3.0 is the boundary the #72 perceptual bridge
#: measured as empirically clean (fully-in-gamut sets stay under it, clipped
#: sets land far above — ``xicclu_runner.to_device_via_profile``); 1.5 is the
#: tightened "comfortably inside" variant. PROVISIONAL until the first real
#: print confirms them.
MARGIN_THRESHOLD_DE76 = {MARGIN_SAFE: 1.5, MARGIN_FULL: 3.0}

#: §7 — the module's one intent choice, applied to BOTH the chart build and
#: the reading, recorded in the reference file. Absolute matches the practice
#: this feature replaces; media-relative isolates the profile from the paper
#: white. Stored under these names; xicclu letters via :func:`intent_letter`.
INTENT_ABSOLUTE = "absolute"
INTENT_RELATIVE = "relative"
_INTENT_LETTER = {INTENT_ABSOLUTE: "a", INTENT_RELATIVE: "r"}

#: The eight cube corners in the measurement report's own order
#: (``measurement_report.CUBE_CORNERS``: W K R G B C M Y), device 0..100.
CORNER_DEVICES: "tuple[tuple[float, float, float], ...]" = (
    (100.0, 100.0, 100.0), (0.0, 0.0, 0.0),
    (100.0, 0.0, 0.0), (0.0, 100.0, 0.0), (0.0, 0.0, 100.0),
    (0.0, 100.0, 100.0), (100.0, 0.0, 100.0), (100.0, 100.0, 0.0),
)


class GamutTargetError(RuntimeError):
    """Selection could not run (missing master set, unusable profile, …)."""


def intent_letter(intent: str) -> str:
    return _INTENT_LETTER.get(intent, "a")


def master_set_path() -> Path:
    return Path(resource_path(MASTER_SET_ASSET))


@dataclass
class GamutSelection:
    """The outcome of filtering the master set through one profile."""

    master_version: str
    master_total: int             #: size of the master set
    in_gamut_total: int           #: coverage — reachable master colours
    requested: int                #: what the user asked for
    intent: str                   #: "absolute" | "relative"
    margin: str                   #: "safe" | "full"
    #: The chart body, in master (nested) order: (master_index, master Lab,
    #: device 0..100). len == min(requested, in_gamut_total).
    targets: "list[tuple[int, tuple[float, float, float], tuple[float, ...]]]" = field(default_factory=list)
    #: The §9a corners: (device, ideal sRGB Lab), appended after the targets.
    corners: "list[tuple[tuple[float, ...], tuple[float, float, float]]]" = field(default_factory=list)

    @property
    def achieved(self) -> int:
        return len(self.targets)

    @property
    def total_patches(self) -> int:
        return len(self.targets) + len(self.corners)


def load_master_labs(path: "Path | None" = None) -> "list[tuple[float, float, float]]":
    """The master set as Lab (D50), in its published (nested) order.

    The set is generated with an sRGB conditioning profile, so targen's XYZ
    column is D65-referenced; it is Bradford-adapted to D50 here with exactly
    the machinery the measurement report uses for design values, so the
    targets and the report speak the same white point.
    """
    from workflow.measurement_report import (_bradford_d65_to_d50,
                                             _design_xyz_is_d65,
                                             _design_xyz_to_100)
    from workflow.ti3_analysis import parse_ti3, xyz_to_lab
    import numpy as np
    p = Path(path) if path is not None else master_set_path()
    if not p.is_file():
        raise GamutTargetError(
            f"the master colour set is missing: {p.name}")
    data = parse_ti3(p)
    xyz = _design_xyz_to_100(np.asarray(data.xyz, dtype=float))
    adapt = _design_xyz_is_d65(data.keywords)
    out = []
    for x, y, z in xyz:
        if adapt:
            x, y, z = _bradford_d65_to_d50(float(x), float(y), float(z))
        out.append(xyz_to_lab((float(x) / 100.0, float(y) / 100.0,
                               float(z) / 100.0)))
    return out


def _corner_ideal_labs() -> "list[tuple[float, float, float]]":
    """The corners' reference Lab — the ideal device corners read as sRGB,
    exactly the reading the report's design reference has always used, so the
    corner trend stays comparable across chart kinds."""
    from workflow.xicclu_runner import _srgb_to_lab_rows
    return _srgb_to_lab_rows(list(CORNER_DEVICES))


def select_gamut_targets(
    profile: Path,
    count: int,
    margin: str,
    intent: str,
    *,
    bin_dir: "str | Path",
    master_path: "Path | None" = None,
    runner: "Callable[..., subprocess.CompletedProcess]" = subprocess.run,
) -> GamutSelection:
    """Filter the master set through *profile* and pick the first *count*
    reachable colours (nested order), plus the eight corners.

    The round trip: master Lab → B2A → device → A2B → Lab′. A colour the
    profile can reach comes back within interpolation error; a clipped one
    lands on the gamut surface and moves far. The margin picks the threshold.
    """
    from workflow.xicclu_runner import XiccluError, backward_device, forward_lab
    profile = Path(profile)
    if not profile.is_file():
        raise GamutTargetError(f"the profile file is missing: {profile}")
    if count < 1:
        raise GamutTargetError("the requested patch count must be at least 1")
    threshold = MARGIN_THRESHOLD_DE76.get(margin)
    if threshold is None:
        raise GamutTargetError(f"unknown margin {margin!r}")
    letter = intent_letter(intent)

    labs = load_master_labs(master_path)
    try:
        # RGB output profiles have no K channel — no -k rule.
        device = backward_device(labs, profile, bin_dir, intent=letter,
                                 k_rule=None, runner=runner)
        back = forward_lab(device, profile, bin_dir, intent=letter,
                           runner=runner)
    except XiccluError as exc:
        raise GamutTargetError(str(exc)) from exc

    selection = GamutSelection(
        master_version=MASTER_SET_VERSION, master_total=len(labs),
        in_gamut_total=0, requested=int(count),
        intent=intent, margin=margin)
    for i, (lab, dev, lab2) in enumerate(zip(labs, device, back)):
        moved = math.dist(lab, lab2)
        if moved <= threshold:
            selection.in_gamut_total += 1
            if len(selection.targets) < count:
                selection.targets.append((i, lab, tuple(dev)))
    selection.corners = list(zip(CORNER_DEVICES, _corner_ideal_labs()))
    log.info("gamut selection: %d of %d master colours in gamut (%s margin), "
             "%d requested, %d chosen + %d corners",
             selection.in_gamut_total, selection.master_total, margin,
             count, selection.achieved, len(selection.corners))
    return selection


# ---------------------------------------------------------------------------
# The chart .ti1 and the colorimetric reference
# ---------------------------------------------------------------------------

def write_gamut_ti1(selection: GamutSelection, out_path: Path) -> Path:
    """The chart's patch list: the chosen device values, corners last.

    Uses the battle-tested 3-table RGB emitter, so printtarg and the ChromIQ
    layout engine both accept the file exactly as they do any other .ti1.
    """
    from workflow.i1profiler_import import RgbPatch, write_ti1
    patches = [RgbPatch(*dev) for _i, _lab, dev in selection.targets]
    patches += [RgbPatch(*dev) for dev, _lab in selection.corners]
    if not patches:
        raise GamutTargetError("nothing to write — no colour is in gamut")
    return write_ti1(patches, Path(out_path))


def reference_rows(selection: GamutSelection):
    """(sample_id, device, Lab) in chart order — targets first, corners last,
    SAMPLE_ID 1..N matching :func:`write_gamut_ti1`'s order exactly."""
    rows = []
    sid = 1
    for _i, lab, dev in selection.targets:
        rows.append((sid, dev, lab))
        sid += 1
    for dev, lab in selection.corners:
        rows.append((sid, dev, lab))
        sid += 1
    return rows


def corner_sample_ids(selection: GamutSelection) -> "list[int]":
    n = len(selection.targets)
    return [n + 1 + i for i in range(len(selection.corners))]


def write_colorimetric_reference(selection: GamutSelection, out_path: Path) -> Path:
    """The stored colorimetric targets (§11 step 5) — one file, three jobs:
    the report's reference, the Print tab's force-Raw marker (feature A reads
    its presence), and the §5.4 record of set version, intent and margin."""
    from workflow.ti3_analysis import _lab_to_xyz_array
    import numpy as np
    rows = reference_rows(selection)
    corner_ids = corner_sample_ids(selection)
    labs = np.array([lab for _sid, _dev, lab in rows], dtype=float)
    xyzs = _lab_to_xyz_array(labs)          # 0..100, D50
    lines = [
        "CTI3   ",
        "",
        'DESCRIPTOR "ChromIQ colorimetric verification reference"',
        'ORIGINATOR "ChromIQ"',
        f'CREATED "{datetime.now().strftime("%a %b %d %H:%M:%S %Y")}"',
        'DEVICE_CLASS "OUTPUT"',
        'COLOR_REP "RGB_XYZ"',
        f'CHROMIQ_SET_VERSION "{selection.master_version}"',
        f'CHROMIQ_INTENT "{selection.intent}"',
        f'CHROMIQ_MARGIN "{selection.margin}"',
        f'CHROMIQ_MASTER_TOTAL "{selection.master_total}"',
        f'CHROMIQ_IN_GAMUT "{selection.in_gamut_total}"',
        f'CHROMIQ_REQUESTED "{selection.requested}"',
        f'CHROMIQ_CORNER_IDS "{" ".join(str(i) for i in corner_ids)}"',
        "",
        "NUMBER_OF_FIELDS 10",
        "BEGIN_DATA_FORMAT",
        "SAMPLE_ID RGB_R RGB_G RGB_B XYZ_X XYZ_Y XYZ_Z LAB_L LAB_A LAB_B",
        "END_DATA_FORMAT",
        "",
        f"NUMBER_OF_SETS {len(rows)}",
        "BEGIN_DATA",
    ]
    for (sid, dev, lab), xyz in zip(rows, xyzs):
        lines.append(" ".join(
            [str(sid)]
            + [f"{v:.4f}" for v in dev]
            + [f"{float(v):.4f}" for v in xyz]
            + [f"{float(v):.4f}" for v in lab]))
    lines += ["END_DATA", ""]
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    log.info("colorimetric reference written: %s (%d rows, %d corners)",
             out_path.name, len(rows), len(corner_ids))
    return out_path


def read_colorimetric_reference(path: Path) -> "dict | None":
    """{"labs": {sample_id_str: (L,a,b)}, "corner_ids": set[str], meta…} — or
    None when the file is missing or unreadable. Sample ids are strings, the
    same shape ``parse_ti3`` gives the report, so pairing needs no casts."""
    path = Path(path)
    if not path.is_file():
        return None
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None
    keywords: dict = {}
    fields: "list[str]" = []
    labs: dict = {}
    in_fmt = in_data = False
    for raw in text.splitlines():
        s = raw.strip()
        if not s:
            continue
        if s == "BEGIN_DATA_FORMAT":
            in_fmt = True
            continue
        if s == "END_DATA_FORMAT":
            in_fmt = False
            continue
        if s == "BEGIN_DATA":
            in_data = True
            continue
        if s == "END_DATA":
            in_data = False
            continue
        if in_fmt:
            fields += s.split()
            continue
        if in_data:
            cells = s.split()
            if len(cells) != len(fields):
                continue
            row = dict(zip(fields, cells))
            try:
                labs[row["SAMPLE_ID"]] = (float(row["LAB_L"]),
                                          float(row["LAB_A"]),
                                          float(row["LAB_B"]))
            except (KeyError, ValueError):
                continue
            continue
        if " " in s and s.split(None, 1)[1].startswith('"'):
            key, val = s.split(None, 1)
            keywords[key] = val.strip().strip('"')
    if not labs:
        return None
    corner_ids = set((keywords.get("CHROMIQ_CORNER_IDS") or "").split())
    return {
        "labs": labs,
        "corner_ids": corner_ids,
        "set_version": keywords.get("CHROMIQ_SET_VERSION", ""),
        "intent": keywords.get("CHROMIQ_INTENT", ""),
        "margin": keywords.get("CHROMIQ_MARGIN", ""),
        "master_total": keywords.get("CHROMIQ_MASTER_TOTAL", ""),
        "in_gamut": keywords.get("CHROMIQ_IN_GAMUT", ""),
    }


def mark_chart_as_colorimetric(ti2_path: Path, reference_path: Path) -> None:
    """Record the reference in the chart's ``.channels.json`` sidecar, so a
    chart whose reference file goes missing still *claims* one — feature A's
    A3c case, which forces Raw rather than risking a double conversion."""
    sidecar = Path(ti2_path).with_name(f"{Path(ti2_path).stem}.channels.json")
    data: dict = {}
    if sidecar.is_file():
        try:
            data = json.loads(sidecar.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            data = {}
    data["colorimetric_reference"] = Path(reference_path).name
    try:
        sidecar.write_text(json.dumps(data, indent=2), encoding="utf-8")
    except OSError:
        log.warning("could not mark %s as colorimetric", sidecar, exc_info=True)
