"""A verification target chosen from the profile's own gamut (#133, feature B).

The master set is ONE deterministic, versioned list of colours (issue #133
§5.1), generated by Argyll's ``targen -t`` — *Incremental Far Point
Distribution*, which picks each point as far as possible from everything
already picked, so **every prefix is itself a well-spread set** (§5.2's
nesting, by construction; verified byte-compared in the planning session).
The bundled set is marked **PROVISIONAL** (§5.4 / the plan's one irreversible
decision): it may be re-cut freely until somebody outside this project relies
on a report that names it, and only then is it frozen under a version number.

For a given profile this module *selects*: every master colour is pushed
backward through the profile (its B2A — "which ink amounts produce this
colour?") and forward again (its A2B), and the round-trip ΔE76 says whether
the profile can actually reach it — **together with the ink amount itself,
which has to exist**: the numeric inverse answers outside the device cube and
the forward leg extrapolates back, so a colour needing device 107.69 round
trips perfectly and is still unprintable (:func:`device_is_printable`). Two
numbers fall out, answering two different questions (§5.1):

* **coverage** — how many of the master set this profile can print at all;
* the **chart** — reachable colours in master order, with one adjustment for
  small charts: the master list opens with a 38-entry neutral block (4 white,
  4 black, a 30-step grey wedge — the ``-e4 -B4 -g32`` of its recipe), and
  taking it whole meant a ~100-colour chart was more than a third neutral
  (Sebastian, on his ColorMunki plain-paper chart, 2026-08-12). The neutral
  block now has a **budget of about one patch in eight** (floor 6, and never
  more than half the chart): one white, one black, and grey steps taken in a
  fixed ends-first bisection order — so every prefix of the wedge is evenly
  spaced AND a subset of every longer one. The master's duplicate white/black
  patches are never budget picks (the unconditional corners already anchor
  both ends); unused budget flows to the body. The remaining slots go to the
  first reachable chromatic colours in master order, unchanged. From about
  260 colours up the budget covers white, black and every grey step.
  Everything stays deterministic (same profile + same count = same chart),
  and any smaller chart's colours are a subset of any larger chart's for the
  same profile.

The eight cube corners are appended **unconditionally, outside the filter**
(§9a): they measure how far the ink and paper reach, which is a property the
profile has no say in, so the gamut filter must never remove them. They are
excluded from the accuracy statistics and reported in their own section.

The chart's ``.ti2`` ends up holding **final device values** — the profile is
applied at *build* time — so the sheet must print **raw**; the stored
colorimetric reference beside the chart is both the report's yardstick and the
marker the Print tab already reads to force Raw (feature A, §3.1a).

Process model: ``subprocess.run`` through :mod:`workflow.xicclu_runner`'s
injectable runners — never the ArgyllRunner singleton, always with a timeout.
"""
from __future__ import annotations

import hashlib
import json
import math
import struct
import subprocess
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Callable, Sequence

from core.logger import get_logger
from core.resource_path import resource_path

log = get_logger(__name__)

#: The published master set (PROVISIONAL — see the module docstring).
MASTER_SET_VERSION = "PROVISIONAL-r1"
MASTER_SET_ASSET = f"assets/verification/chromiq-verification-set-{MASTER_SET_VERSION}.ti1"

#: §6 — the two margin choices. "Safe" keeps targets away from the gamut
#: boundary with a tightened round-trip threshold; "full" allows everything
#: the profile can technically reach.
MARGIN_SAFE = "safe"
MARGIN_FULL = "full"
#: ΔE76 round-trip thresholds. 3.0 is the boundary the #72 perceptual bridge
#: measured as empirically clean (fully-in-gamut sets stay under it, clipped
#: sets land far above — ``xicclu_runner.to_device_via_profile``); 1.5 is the
#: tightened "comfortably inside" variant. PROVISIONAL until the first real
#: print confirms them.
MARGIN_THRESHOLD_DE76 = {MARGIN_SAFE: 1.5, MARGIN_FULL: 3.0}

#: §7 — the module's one intent choice, applied to BOTH the chart build and
#: the reading, recorded in the reference file. Absolute matches the practice
#: this feature replaces; media-relative isolates the profile from the paper
#: white. Stored under these names; xicclu letters via :func:`intent_letter`.
INTENT_ABSOLUTE = "absolute"
INTENT_RELATIVE = "relative"
_INTENT_LETTER = {INTENT_ABSOLUTE: "a", INTENT_RELATIVE: "r"}

#: The eight cube corners in the measurement report's own order
#: (``measurement_report.CUBE_CORNERS``: W K R G B C M Y), device 0..100.
CORNER_DEVICES: "tuple[tuple[float, float, float], ...]" = (
    (100.0, 100.0, 100.0), (0.0, 0.0, 0.0),
    (100.0, 0.0, 0.0), (0.0, 100.0, 0.0), (0.0, 0.0, 100.0),
    (0.0, 100.0, 100.0), (100.0, 0.0, 100.0), (100.0, 100.0, 0.0),
)


#: The printable device cube. Argyll speaks 0..100 per channel and there is
#: no ink amount outside it: printtarg and the ChromIQ layout engine both
#: clip what they render, so a value beyond these bounds can only mislead
#: whoever reads the file.
DEVICE_MIN = 0.0
DEVICE_MAX = 100.0
#: How far outside the cube is still the same value. Arithmetic dust only —
#: measured over the whole 5,960-colour master set through two real profiles,
#: nothing at all lands in (0, 0.01] outside the cube, so this tolerance
#: decides no colour's fate; it exists so a 100.0000001 from the inverse is
#: not read as a different number from 100.
DEVICE_EPS = 0.01


def device_is_printable(device: "Sequence[float]") -> bool:
    """Is this ink amount one the printer can actually be asked for?

    **xicclu's numeric inverse answers outside the device cube.** Asked for a
    colour the profile cannot reach, ``-fif`` extrapolates the forward table
    and hands back device values above 100 (measured: 304 of 5,960 master
    colours through a 210-patch ``colprof -ql -aG`` profile, the largest
    107.69). The round trip does not catch it, because the forward leg
    extrapolates the same way and the two errors cancel: those colours come
    back 0.000 ΔE00 from their aim while no printer can print them.
    """
    return all(DEVICE_MIN - DEVICE_EPS <= float(v) <= DEVICE_MAX + DEVICE_EPS
               for v in device)


def snap_to_device_cube(device: "Sequence[float]") -> "tuple[float, ...]":
    """*device* with each channel put back inside 0..100.

    The last line of defence, applied by both file writers so the chart and
    its colorimetric reference can never describe the same patch with two
    different ink amounts. After :func:`select_gamut_targets` it moves
    nothing further than :data:`DEVICE_EPS`, because a colour that needs more
    than that is not selected at all.
    """
    return tuple(min(DEVICE_MAX, max(DEVICE_MIN, float(v))) for v in device)


class GamutTargetError(RuntimeError):
    """Selection could not run (missing master set, unusable profile, …)."""


def intent_letter(intent: str) -> str:
    return _INTENT_LETTER.get(intent, "a")


def master_set_path() -> Path:
    return Path(resource_path(MASTER_SET_ASSET))


@dataclass
class GamutSelection:
    """The outcome of filtering the master set through one profile."""

    master_version: str
    master_total: int             #: size of the master set
    in_gamut_total: int           #: coverage — reachable master colours
    requested: int                #: what the user asked for
    intent: str                   #: "absolute" | "relative"
    margin: str                   #: "safe" | "full"
    #: The chart body, in master (nested) order: (master_index, master Lab,
    #: device 0..100). len == min(requested, in_gamut_total).
    targets: "list[tuple[int, tuple[float, float, float], tuple[float, ...]]]" = field(default_factory=list)
    #: The §9a corners: (device, ideal sRGB Lab), appended after the targets.
    corners: "list[tuple[tuple[float, ...], tuple[float, float, float]]]" = field(default_factory=list)

    @property
    def achieved(self) -> int:
        return len(self.targets)

    @property
    def total_patches(self) -> int:
        return len(self.targets) + len(self.corners)


def load_master_labs(path: "Path | None" = None) -> "list[tuple[float, float, float]]":
    """The master set as Lab (D50), in its published (nested) order.

    The set is generated with an sRGB conditioning profile, so targen's XYZ
    column is D65-referenced; it is Bradford-adapted to D50 here with exactly
    the machinery the measurement report uses for design values, so the
    targets and the report speak the same white point.
    """
    from workflow.measurement_report import (_bradford_d65_to_d50,
                                             _design_xyz_is_d65,
                                             _design_xyz_to_100)
    from workflow.ti3_analysis import parse_ti3, xyz_to_lab
    import numpy as np
    p = Path(path) if path is not None else master_set_path()
    if not p.is_file():
        raise GamutTargetError(
            f"the master colour set is missing: {p.name}")
    data = parse_ti3(p)
    xyz = _design_xyz_to_100(np.asarray(data.xyz, dtype=float))
    adapt = _design_xyz_is_d65(data.keywords)
    out = []
    for x, y, z in xyz:
        if adapt:
            x, y, z = _bradford_d65_to_d50(float(x), float(y), float(z))
        out.append(xyz_to_lab((float(x) / 100.0, float(y) / 100.0,
                               float(z) / 100.0)))
    return out


def _corner_ideal_labs() -> "list[tuple[float, float, float]]":
    """The corners' reference Lab — the ideal device corners read as sRGB,
    exactly the reading the report's design reference has always used, so the
    corner trend stays comparable across chart kinds."""
    from workflow.xicclu_runner import _srgb_to_lab_rows
    return _srgb_to_lab_rows(list(CORNER_DEVICES))


def _master_keywords(path: "Path | None" = None) -> dict:
    """The master set's own header keywords ({} when unreadable)."""
    from workflow.ti3_analysis import parse_ti3
    p = Path(path) if path is not None else master_set_path()
    try:
        return dict(parse_ti3(p).keywords or {})
    except Exception:      # noqa: BLE001 — no keywords just means no budgeting
        return {}


def _neutral_prefix_counts(keywords: dict) -> "tuple[int, int, int]":
    """``(whites, blacks, mid greys)`` at the START of the master order, read
    from the set's own header (targen stamps its recipe there). A master
    without the keywords — a test fixture, a custom set — gets ``(0, 0, 0)``
    and the selection stays the plain first-*n* prefix."""
    try:
        w = int(keywords.get("WHITE_COLOR_PATCHES", 0))
        k = int(keywords.get("BLACK_COLOR_PATCHES", 0))
        # targen counts white and black as the wedge's own endpoints.
        g = max(0, int(keywords.get("COMP_GREY_STEPS", 0)) - 2)
    except (TypeError, ValueError):
        return (0, 0, 0)
    return (max(0, w), max(0, k), g)


def _neutral_budget(count: int) -> int:
    """How many of *count* requested colours the neutral block may take:
    about one in eight, floor 6, never more than half the chart."""
    return min(max(6, round(count / 8)), count // 2)


def _spread_order(n: int) -> "list[int]":
    """``0..n-1`` in an ends-first bisection order: every prefix is an
    approximately even sample of the range, and every prefix contains all
    shorter ones — which is what keeps a small chart's grey steps a subset
    of a large chart's."""
    if n <= 0:
        return []
    if n == 1:
        return [0]
    import heapq
    order = [0, n - 1]
    seen = {0, n - 1}
    heap = [(-(n - 1), 0, n - 1)]
    while heap and len(order) < n:
        _neg, lo, hi = heapq.heappop(heap)
        if hi - lo < 2:                     # no interior point left in here
            continue
        mid = (lo + hi) // 2
        if mid not in seen:
            order.append(mid)
            seen.add(mid)
        heapq.heappush(heap, (-(mid - lo), lo, mid))
        heapq.heappush(heap, (-(hi - mid), mid, hi))
    for i in range(n):                      # safety net, ascending
        if i not in seen:
            order.append(i)
    return order


#: (profile path, profile digest, intent letter, bin dir, colour count, colour
#: digest) → (device, back). Bounded, because each entry holds two rows per
#: colour asked about.
_ROUND_TRIP_CACHE: "dict[tuple, tuple[list, list]]" = {}
_ROUND_TRIP_CACHE_MAX = 3


def clear_round_trip_cache() -> None:
    """Forget every remembered round trip. For tests, and for anything that
    wants the profiles re-read from disk."""
    _ROUND_TRIP_CACHE.clear()


def _round_trip(
    labs: "list[tuple[float, float, float]]",
    profile: Path,
    bin_dir: "str | Path",
    letter: str,
    runner: "Callable[..., subprocess.CompletedProcess]",
) -> "tuple[list, list]":
    """Lab → device → Lab′ through *profile*, the one place that asks.

    **THE MARGIN IS NOT PART OF THE QUESTION.** It is a threshold applied to
    the answer, and so is the patch count, so re-asking xicclu when only one
    of those changed spends seconds re-deriving numbers that cannot have
    moved. Both entry points share this function and its memo, so flicking
    Margin after the reach is known costs nothing.

    Only a REAL ``subprocess.run`` is remembered. An injected runner is a
    test's stand-in for the process and its answers are the test's business,
    so those callers always re-run.
    """
    from workflow.xicclu_runner import XiccluError, backward_device, forward_lab

    key = None
    if runner is subprocess.run:
        try:
            # THE PROFILE'S CONTENTS, not its name and timestamp. `shutil.copy2`
            # PRESERVES the modification time, and ChromIQ really does copy an
            # ICC onto a run's own profile path that way (`ui/ti2_loader.py`
            # importing a measurement with its profile beside it), so path +
            # size + mtime can describe two different profiles. Reading it
            # costs about 2 ms against the second this saves, and it makes a
            # stale answer impossible rather than unlikely.
            h = hashlib.blake2b(profile.read_bytes(), digest_size=16)
            # THE COLOURS THEMSELVES, digested too, because `flags_in_gamut` is
            # handed an arbitrary list by the measurement report: a key that
            # said only how MANY there were would serve one set of colours the
            # answer computed for a different set of the same length.
            c = hashlib.blake2b(digest_size=16)
            for lab in labs:
                c.update(struct.pack("<3d", *lab))
            # The PATH joins both digests. Two identical profiles in two places
            # then get an entry each, which is a little wasteful and never
            # wrong; keying on the contents alone made every caller holding the
            # same small stand-in profile share one answer, which is how this
            # broke `test_gamut_target.py` when it was first written.
            key = (str(profile.resolve()), h.hexdigest(), letter,
                   str(bin_dir), len(labs), c.hexdigest())
        except (OSError, struct.error, TypeError):
            key = None
    if key is not None and key in _ROUND_TRIP_CACHE:
        return _ROUND_TRIP_CACHE[key]

    try:
        # RGB output profiles have no K channel — no -k rule.
        # THE NUMERIC INVERSE, because this device value is going on paper.
        # `-fb` reads the profile's baked B2A table, which is a fast
        # approximation of an inverse; over the eleven bundled sets it lands
        # 0.366 dE00 from the aim on average against 0.052 for `-fif`, and 659
        # of 792 patches inside 0.5 against 770. It cost 0.17 s for 1,617.
        device = backward_device(labs, profile, bin_dir, intent=letter,
                                 k_rule=None, numeric_inverse=True,
                                 runner=runner)
        back = forward_lab(device, profile, bin_dir, intent=letter,
                           runner=runner)
    except XiccluError as exc:
        raise GamutTargetError(str(exc)) from exc

    if key is not None:
        while len(_ROUND_TRIP_CACHE) >= _ROUND_TRIP_CACHE_MAX:
            _ROUND_TRIP_CACHE.pop(next(iter(_ROUND_TRIP_CACHE)))
        _ROUND_TRIP_CACHE[key] = (device, back)
    return device, back


def select_gamut_targets(
    profile: Path,
    count: int,
    margin: str,
    intent: str,
    *,
    bin_dir: "str | Path",
    master_path: "Path | None" = None,
    runner: "Callable[..., subprocess.CompletedProcess]" = subprocess.run,
) -> GamutSelection:
    """Filter the master set through *profile* and pick *count* reachable
    colours, plus the eight corners.

    The round trip: master Lab → B2A → device → A2B → Lab′. A colour the
    profile can reach comes back within interpolation error; a clipped one
    lands on the gamut surface and moves far. The margin picks the threshold.
    A colour whose ink amount falls outside the device cube is not reachable
    whatever the round trip says (:func:`device_is_printable`), so it counts
    against neither ``in_gamut_total`` nor the chart.

    The pick is the first *count* reachable colours in master order, EXCEPT
    that the master's opening neutral block (white, black, grey wedge — read
    from the set's own header) is capped at :func:`_neutral_budget` so a
    small chart is not swallowed by greys; see the module docstring. The
    result is deterministic, and a smaller chart's colours are a subset of a
    larger chart's for the same profile.
    """
    profile = Path(profile)
    if not profile.is_file():
        raise GamutTargetError(f"the profile file is missing: {profile}")
    if count < 1:
        raise GamutTargetError("the requested patch count must be at least 1")
    threshold = MARGIN_THRESHOLD_DE76.get(margin)
    if threshold is None:
        raise GamutTargetError(f"unknown margin {margin!r}")
    letter = intent_letter(intent)

    labs = load_master_labs(master_path)
    device, back = _round_trip(labs, profile, bin_dir, letter, runner)

    selection = GamutSelection(
        master_version=MASTER_SET_VERSION, master_total=len(labs),
        in_gamut_total=0, requested=int(count),
        intent=intent, margin=margin)

    # THE ROUND TRIP ALONE IS NOT THE QUESTION: A COLOUR IS REACHABLE ONLY IF
    # ITS INK AMOUNT EXISTS. `-fif` extrapolates outside the device cube, and
    # the forward leg extrapolates back, so a colour needing device 107.69
    # returns 0.000 ΔE00 from its aim and reads as comfortably in gamut. It is
    # not: the printer receives 100, and what it prints is up to 8.86 ΔE00
    # from the aim the chart's reference file would store beside it (measured
    # over the whole master set, 238 such colours, mean 2.34). Keeping the
    # patch and clamping it writes an aim the print provably cannot hit, and
    # the verification report then charges that error to the printer. Dropping
    # it costs nothing: the next reachable colour in master order takes the
    # slot, every prefix stays nested, and the chart is the size asked for.
    passing = []
    unprintable = 0
    for i, (lab, lab2) in enumerate(zip(labs, back)):
        if math.dist(lab, lab2) > threshold:
            continue
        if not device_is_printable(device[i]):
            unprintable += 1
            continue
        passing.append(i)
    selection.in_gamut_total = len(passing)
    if unprintable:
        log.info("gamut selection: %d master colours round-tripped inside the "
                 "%s margin but need ink amounts outside 0..100 and are not "
                 "reachable", unprintable, margin)

    # The neutral block at the head of the master order, budgeted. The
    # header says where it ends; the chroma check makes sure the entries
    # really are neutral, so a re-cut master with a different layout can
    # never make the budget pick coloured patches as "greys".
    n_w, n_k, n_g = _neutral_prefix_counts(_master_keywords(master_path))
    prefix_end = n_w + n_k + n_g

    def _is_neutral(i: int) -> bool:
        return math.hypot(labs[i][1], labs[i][2]) < 1.0

    whites = [i for i in passing if i < n_w and _is_neutral(i)]
    blacks = [i for i in passing if n_w <= i < n_w + n_k and _is_neutral(i)]
    greys = [i for i in passing
             if n_w + n_k <= i < prefix_end and _is_neutral(i)]
    neutral_all = set(whites) | set(blacks) | set(greys)

    chosen: "list[int]" = []
    if prefix_end:
        budget = _neutral_budget(count)
        if whites and len(chosen) < budget:
            chosen.append(whites[0])
        if blacks and len(chosen) < budget:
            chosen.append(blacks[0])
        # Grey steps in ends-first bisection order: evenly spaced at every
        # budget, and every smaller budget's picks are inside every larger
        # one's. The master's duplicate white/black patches are never budget
        # picks — the corners already anchor both ends, so unused budget is
        # better spent on real colours (it simply flows to the body below).
        g_room = budget - len(chosen)
        if g_room > 0 and greys:
            picks = _spread_order(len(greys))[:g_room]
            chosen.extend(greys[j] for j in sorted(picks))

    body = [i for i in passing if i not in neutral_all]
    chosen.extend(body[:count - len(chosen)])
    if len(chosen) < count:
        # A gamut so small (or a chart so large) that the body runs dry:
        # top up with the remaining reachable neutrals rather than shipping
        # a shorter chart than the reachable colours allow.
        have = set(chosen)
        rest = [i for i in passing if i not in have]
        chosen.extend(rest[:count - len(chosen)])

    for i in sorted(chosen):
        selection.targets.append((i, labs[i], snap_to_device_cube(device[i])))
    selection.corners = list(zip(CORNER_DEVICES, _corner_ideal_labs()))
    log.info("gamut selection: %d of %d master colours in gamut (%s margin), "
             "%d requested, %d chosen (%d neutral) + %d corners",
             selection.in_gamut_total, selection.master_total, margin,
             count, selection.achieved,
             sum(1 for t in selection.targets if t[0] in neutral_all),
             len(selection.corners))
    return selection


def flags_in_gamut(
    labs: "list[tuple[float, float, float]]",
    profile: Path,
    bin_dir: "str | Path",
    *,
    margin: str = MARGIN_SAFE,
    intent: str = "absolute",
    runner: "Callable[..., subprocess.CompletedProcess]" = subprocess.run,
) -> "list[bool]":
    """One in/out-of-gamut flag per Lab colour, same round trip and the same
    thresholds as :func:`select_gamut_targets` — Lab → B2A → device → A2B →
    Lab′; a reachable colour comes back within interpolation error, a clipped
    one lands on the gamut surface and moves far. Used by the measurement
    report's split statistics (Knut, 2026-08-10).

    Shares :func:`_round_trip` with :func:`select_gamut_targets`, so the
    numeric inverse is asked for in one place and the two can never drift into
    answering the same question differently."""
    profile = Path(profile)
    if not profile.is_file():
        raise GamutTargetError(f"the profile file is missing: {profile}")
    threshold = MARGIN_THRESHOLD_DE76.get(margin)
    if threshold is None:
        raise GamutTargetError(f"unknown margin {margin!r}")
    letter = intent_letter(intent)
    _device, back = _round_trip(list(labs), profile, bin_dir, letter, runner)
    return [math.dist(lab, lab2) <= threshold
            for lab, lab2 in zip(labs, back)]


# ---------------------------------------------------------------------------
# The chart .ti1 and the colorimetric reference
# ---------------------------------------------------------------------------

def write_gamut_ti1(selection: GamutSelection, out_path: Path) -> Path:
    """The chart's patch list: the chosen device values, corners last.

    Uses the battle-tested 3-table RGB emitter, so printtarg and the ChromIQ
    layout engine both accept the file exactly as they do any other .ti1.

    **No ink amount outside 0..100 reaches the file** (:func:`snap_to_device_cube`,
    applied identically by :func:`write_colorimetric_reference` so the two can
    never describe one patch two ways). With a selection from
    :func:`select_gamut_targets` this changes nothing — such a colour is not
    selected — but one patch above 100 in a chart is enough to make the
    measurement report read the whole chart as 0..255 code values and divide
    every device value by 2.55, and then not one cube corner is found.
    """
    from workflow.i1profiler_import import RgbPatch, write_ti1
    patches = [RgbPatch(*snap_to_device_cube(dev))
               for _i, _lab, dev in selection.targets]
    patches += [RgbPatch(*snap_to_device_cube(dev))
                for dev, _lab in selection.corners]
    if not patches:
        raise GamutTargetError("nothing to write — no colour is in gamut")
    return write_ti1(patches, Path(out_path))


def reference_rows(selection: GamutSelection):
    """(sample_id, device, Lab) in chart order — targets first, corners last,
    SAMPLE_ID 1..N matching :func:`write_gamut_ti1`'s order exactly."""
    rows = []
    sid = 1
    for _i, lab, dev in selection.targets:
        rows.append((sid, snap_to_device_cube(dev), lab))
        sid += 1
    for dev, lab in selection.corners:
        rows.append((sid, snap_to_device_cube(dev), lab))
        sid += 1
    return rows


def corner_sample_ids(selection: GamutSelection) -> "list[int]":
    n = len(selection.targets)
    return [n + 1 + i for i in range(len(selection.corners))]


def write_colorimetric_reference(selection: GamutSelection, out_path: Path) -> Path:
    """The stored colorimetric targets (§11 step 5) — one file, three jobs:
    the report's reference, the Print tab's force-Raw marker (feature A reads
    its presence), and the §5.4 record of set version, intent and margin."""
    from workflow.ti3_analysis import _lab_to_xyz_array
    import numpy as np
    rows = reference_rows(selection)
    corner_ids = corner_sample_ids(selection)
    labs = np.array([lab for _sid, _dev, lab in rows], dtype=float)
    xyzs = _lab_to_xyz_array(labs)          # 0..100, D50
    lines = [
        "CTI3   ",
        "",
        'DESCRIPTOR "ChromIQ colorimetric verification reference"',
        'ORIGINATOR "ChromIQ"',
        f'CREATED "{datetime.now().strftime("%a %b %d %H:%M:%S %Y")}"',
        'DEVICE_CLASS "OUTPUT"',
        'COLOR_REP "RGB_XYZ"',
        f'CHROMIQ_SET_VERSION "{selection.master_version}"',
        f'CHROMIQ_INTENT "{selection.intent}"',
        f'CHROMIQ_MARGIN "{selection.margin}"',
        f'CHROMIQ_MASTER_TOTAL "{selection.master_total}"',
        f'CHROMIQ_IN_GAMUT "{selection.in_gamut_total}"',
        f'CHROMIQ_REQUESTED "{selection.requested}"',
        f'CHROMIQ_CORNER_IDS "{" ".join(str(i) for i in corner_ids)}"',
        "",
        "NUMBER_OF_FIELDS 10",
        "BEGIN_DATA_FORMAT",
        "SAMPLE_ID RGB_R RGB_G RGB_B XYZ_X XYZ_Y XYZ_Z LAB_L LAB_A LAB_B",
        "END_DATA_FORMAT",
        "",
        f"NUMBER_OF_SETS {len(rows)}",
        "BEGIN_DATA",
    ]
    for (sid, dev, lab), xyz in zip(rows, xyzs):
        lines.append(" ".join(
            [str(sid)]
            + [f"{v:.4f}" for v in dev]
            + [f"{float(v):.4f}" for v in xyz]
            + [f"{float(v):.4f}" for v in lab]))
    lines += ["END_DATA", ""]
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    log.info("colorimetric reference written: %s (%d rows, %d corners)",
             out_path.name, len(rows), len(corner_ids))
    return out_path


def read_colorimetric_reference(path: Path) -> "dict | None":
    """{"labs": {sample_id_str: (L,a,b)}, "devices": {sample_id_str: (R,G,B)},
    "corner_ids": set[str], meta…} — or None when the file is missing or
    unreadable. Sample ids are strings, the same shape ``parse_ti3`` gives the
    report, so pairing needs no casts.

    ``devices`` is the chart's OWN record of which ink amount each sample was
    given, which is how the measurement report can tell WHICH corner a
    declared corner id is (the file names the ids, not the corners) without
    depending on the order they were written in."""
    path = Path(path)
    if not path.is_file():
        return None
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None
    keywords: dict = {}
    fields: "list[str]" = []
    labs: dict = {}
    devices: dict = {}
    in_fmt = in_data = False
    for raw in text.splitlines():
        s = raw.strip()
        if not s:
            continue
        if s == "BEGIN_DATA_FORMAT":
            in_fmt = True
            continue
        if s == "END_DATA_FORMAT":
            in_fmt = False
            continue
        if s == "BEGIN_DATA":
            in_data = True
            continue
        if s == "END_DATA":
            in_data = False
            continue
        if in_fmt:
            fields += s.split()
            continue
        if in_data:
            cells = s.split()
            if len(cells) != len(fields):
                continue
            row = dict(zip(fields, cells))
            try:
                labs[row["SAMPLE_ID"]] = (float(row["LAB_L"]),
                                          float(row["LAB_A"]),
                                          float(row["LAB_B"]))
            except (KeyError, ValueError):
                continue
            try:
                devices[row["SAMPLE_ID"]] = (float(row["RGB_R"]),
                                             float(row["RGB_G"]),
                                             float(row["RGB_B"]))
            except (KeyError, ValueError):
                pass          # a reference without ink amounts still has aims
            continue
        if " " in s and s.split(None, 1)[1].startswith('"'):
            key, val = s.split(None, 1)
            keywords[key] = val.strip().strip('"')
    if not labs:
        return None
    corner_ids = set((keywords.get("CHROMIQ_CORNER_IDS") or "").split())
    return {
        "labs": labs,
        "devices": devices,
        "corner_ids": corner_ids,
        "set_version": keywords.get("CHROMIQ_SET_VERSION", ""),
        "intent": keywords.get("CHROMIQ_INTENT", ""),
        "margin": keywords.get("CHROMIQ_MARGIN", ""),
        "master_total": keywords.get("CHROMIQ_MASTER_TOTAL", ""),
        "in_gamut": keywords.get("CHROMIQ_IN_GAMUT", ""),
    }


def mark_chart_as_colorimetric(ti2_path: Path, reference_path: Path) -> None:
    """Record the reference in the chart's ``.channels.json`` sidecar, so a
    chart whose reference file goes missing still *claims* one — feature A's
    A3c case, which forces Raw rather than risking a double conversion."""
    sidecar = Path(ti2_path).with_name(f"{Path(ti2_path).stem}.channels.json")
    data: dict = {}
    if sidecar.is_file():
        try:
            data = json.loads(sidecar.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            data = {}
    data["colorimetric_reference"] = Path(reference_path).name
    try:
        sidecar.write_text(json.dumps(data, indent=2), encoding="utf-8")
    except OSError:
        log.warning("could not mark %s as colorimetric", sidecar, exc_info=True)
