"""Orchestrates colprof for ICC profile creation and installation."""
from __future__ import annotations

import re
import shlex
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Callable

from core.logger import get_logger
from core.platform_paths import icc_install_dir

if TYPE_CHECKING:
    from core.argyll_runner import ArgyllRunner

log = get_logger(__name__)


# Errors that colprof can print when it fails. Each entry pairs a regex that
# captures the dynamic part of the message (filename, value, etc.) with a
# (key, friendly_template) tuple. The key lets the UI choose a bespoke dialog
# (e.g. the FWA-instrument one) instead of the generic failure dialog.
# References point to lines in Argyll 3.5.0 spectro/profile/colprof.c.
_COLPROF_ERROR_PATTERNS: list[tuple[re.Pattern[str], str, str]] = [
    # L673 / L720 — illuminant type mismatch
    (re.compile(r"(?:Target|CIE) illuminant '([^']+)' is wrong measurement type"),
     "illum_type",
     "The illuminant '{0}' isn't compatible with the reference data in your "
     ".ti3 file. Pick a different illuminant in Build Profile → Color Science, "
     "or clear the field to use the default."),
    # L1015 — FWA enabled without viewer/illuminant
    (re.compile(r"FWA compensation only works when viewer and/or illuminant selected"),
     "fwa_needs_illum",
     "FWA compensation requires you to also set a viewing condition and/or "
     "illuminant in Build Profile → Color Science. Either pick one of those, "
     "or disable FWA Compensation."),
    # L1048 — input .ti3 unreadable / corrupt
    (re.compile(r"CGATS file read error\s*:\s*(.+)$"),
     "ti3_read",
     "The measurement file (.ti3) could not be read.\n\nArgyll reported: {0}\n\n"
     "Make sure the file isn't open in another app, hasn't been edited by hand, "
     "and was generated by ChromIQ's Measure step."),
    # L1087 — empty / wrong .ti3
    (re.compile(r"Neither CIE nor spectral data found in file '([^']+)'"),
     "ti3_empty",
     "The measurement file doesn't contain any XYZ/Lab or spectral readings.\n\n"
     "File: {0}\n\nIt looks like the file wasn't fully written by chartread, or "
     "you selected a chart definition (.ti1/.ti2) instead of the measured .ti3."),
    # Emitted from icc/colprof when the .ti3 was measured with a non-UV instrument
    # but FWA was requested. The string is checked verbatim (typo and all) — it
    # matches the Argyll output literally.
    (re.compile(r"doesn't have an FWA illuminent", re.IGNORECASE),
     "fwa_no_uv",
     ""),  # handled by a bespoke dialog (_show_fwa_instrument_error)
]

# Warnings that don't terminate colprof but the user may want to know about.
_COLPROF_WARNING_PATTERNS: list[tuple[re.Pattern[str], str, str]] = [
    # L1018 — intent override only works with srcprof
    (re.compile(r"-t perceptual intent override only works if -s srcprof or -S srcprof is used"),
     "perc_intent_orphan",
     "The perceptual intent override (-t) was ignored because no source profile "
     "(-s / -S) was set."),
    # L1021
    (re.compile(r"-T saturation intent override only works if -S srcprof is used"),
     "sat_intent_orphan",
     "The saturation intent override (-T) was ignored because no source "
     "profile (-S) was set."),
    # L1030
    (re.compile(r"No gamut mapping called for, so -P will produce nothing"),
     "no_gamut_map",
     "Gamut mapping wasn't requested, so -P (gamut preview) produced no output."),
    # L1033
    (re.compile(r"-g srcgam will do nothing without -s srcprof or -S srcprof"),
     "srcgam_orphan",
     "The -g srcgam option was ignored because no source profile was set."),
    # L1066
    (re.compile(r"-i illuminant ignored for emissive reference type"),
     "illum_ignored_emissive",
     "Illuminant setting was ignored — this measurement was made in emissive mode."),
    # L1068
    (re.compile(r"-f FWA compensation ignored for emissive reference type"),
     "fwa_ignored_emissive",
     "FWA compensation was ignored — this measurement was made in emissive mode."),
    # L1150 — over-limit ink budget vs original chart
    (re.compile(r"Ink limit is greater than original chart!\s*\(([\d.]+)%\s*>\s*([\d.]+)%\)"),
     "ink_limit_over",
     "Your ink limit ({0}%) exceeds the maximum measured in the chart ({1}%). "
     "The profile may extrapolate beyond what your printer actually does."),
    # L1168 — black ink limit over chart
    (re.compile(r"Black ink limit greater than original chart!\s*\((\d+)%\s*>\s*(\d+)%\)"),
     "kink_limit_over",
     "Your black ink limit ({0}%) exceeds the maximum measured in the chart ({1}%)."),
    # L1279 / L1281
    (re.compile(r"-a([XY]) not applicable to input profile, using -ax"),
     "input_profile_alg",
     "Algorithm -a{0} isn't applicable to input profiles — colprof fell back to -ax."),
]


def _profile_dir() -> Path:
    return icc_install_dir()


@dataclass
class ProfileParams:
    ti3_path: Path
    description: str = ""
    algorithm: str = "l"
    quality: str = "m"
    b2a_quality: str = ""
    smoothing: float = 0.5
    dark_emphasis: float = 1.0
    gamut_src: str = ""
    manufacturer: str = ""
    model: str = ""
    copyright: str = ""
    no_input_shaper: bool = False
    no_output_shaper: bool = False
    verbose: bool = False        # pass colprof -v (progress + errors visible)
    extra_args: str = ""
    # Color science
    illuminant: str = ""
    observer: str = ""
    fwa_enabled: bool = False
    fwa_illum: str = ""
    src_viewing_cond: str = ""
    dst_viewing_cond: str = ""
    # ICC media attributes & default intent (-Z)
    z_surface: str = ""        # "" = glossy (default), "m" = matte
    z_media_type: str = ""     # "" = reflective (default), "t" = transparent
    z_polarity: str = ""       # "" = positive (default), "n" = negative
    z_color_mode: str = ""     # "" = color (default), "b" = black & white
    z_default_intent: str = "" # "" = not set, "p"/"r"/"s"/"a"
    # Gamut mapping extended
    gamut_sat_src: str = ""
    no_perc_gamut: bool = False
    no_sat_gamut: bool = False
    inv_gamut_map: bool = False
    perc_intent: str = ""
    sat_intent: str = ""
    # Curve / embedding flags
    no_grid_pos: bool = False
    no_embedded_data: bool = False
    # Input-profile white-point handling (#121): wp_mode ∈ {"", "u", "ua", "uc",
    # "scale"} → -u / -ua / -uc / -u <wp_scale>; clip_primaries → -R.
    wp_mode: str = ""
    wp_scale: float = 0.0
    clip_primaries: bool = False
    # Black generation (-k/-K): rule ∈ {"", "z", "h", "x", "r", "p"} ("" =
    # colprof's default ramp, flag not passed). k_locus True = uppercase -K
    # (curve is the proportion of the possible black range, not the K value).
    # The five curve parameters are used only with rule "p".
    k_rule: str = ""
    k_locus: bool = False
    k_stle: float = 0.0
    k_stpo: float = 0.1
    k_enpo: float = 0.9
    k_enle: float = 1.0
    k_shape: float = 1.0
    # Engine-only options (#123) — no colprof flags exist for these; the
    # UI only offers them when the engine's maximum-accuracy mode is
    # active, so the colprof path never sees them set.
    spectral_physics: bool = False
    icc_version: str = "2"
    noise_model: bool = False
    render_style: str = "argyll"


class ProfileBuilder:
    def __init__(self, runner: "ArgyllRunner") -> None:
        self._runner = runner
        self._last_log: str = ""
        # Captured (key, friendly_text) pairs as the tool runs.
        self._matched_errors: list[tuple[str, str]] = []
        self._matched_warnings: list[tuple[str, str]] = []

    # ------------------------------------------------------------------

    def build(
        self,
        params: ProfileParams,
        on_line: Callable[[str], None],
        on_finish: Callable[[int], None],
    ) -> None:
        args = self._build_args(params)
        cwd  = params.ti3_path.parent
        log.info("colprof: %s  [cwd=%s]", " ".join(args), cwd)
        self._last_log = ""
        self._matched_errors = []
        self._matched_warnings = []

        def _accumulate(line: str) -> None:
            self._last_log += line + "\n"
            self._scan_line(line)
            on_line(line)

        self._runner.run(
            "colprof",
            args,
            cwd,
            on_line=_accumulate,
            on_finish=on_finish,
        )

    def _scan_line(self, line: str) -> None:
        for pattern, key, fmt in _COLPROF_ERROR_PATTERNS:
            m = pattern.search(line)
            if m:
                self._matched_errors.append((key, fmt.format(*m.groups()) if fmt else ""))
        for pattern, key, fmt in _COLPROF_WARNING_PATTERNS:
            m = pattern.search(line)
            if m:
                self._matched_warnings.append((key, fmt.format(*m.groups())))

    def primary_failure(self) -> tuple[str, str] | None:
        """Return (key, friendly_message) of the first structured error, or
        None if no known error pattern was matched. The UI can pick a bespoke
        dialog by key (e.g. "fwa_no_uv") or fall back to a generic dialog."""
        return self._matched_errors[0] if self._matched_errors else None

    def last_output(self, n: int = 12) -> str:
        """The last *n* non-blank, non-progress lines colprof printed — shown when
        a build fails without a recognised error pattern, so the real reason
        (whatever colprof actually said) is never swallowed."""
        lines = [ln.rstrip() for ln in self._last_log.splitlines()
                 if ln.strip() and not ln.rstrip().endswith("%")]
        return "\n".join(lines[-n:])

    def captured_warnings(self) -> list[tuple[str, str]]:
        """Structured warnings captured during the most recent run."""
        return list(self._matched_warnings)

    def install_profile(self, icc_path: Path,
                        install_name: "str | None" = None) -> Path:
        """Copy .icc file to the system ICC profile folder. Returns the installed path.

        ``install_name`` (no extension) names the INSTALLED COPY only — Knut's
        "Profile file name same as description for installed copy" checkbox.
        The project's own file always keeps its name; an installed profile of
        the same name is replaced, which is the normal way to update one.
        """
        profile_dir = _profile_dir()
        try:
            profile_dir.mkdir(parents=True, exist_ok=True)
        except PermissionError:
            log.warning("Cannot create profile dir %s — elevation may be required", profile_dir)
            raise
        name = f"{install_name}.icc" if install_name else icc_path.name
        dest = profile_dir / name
        shutil.copy2(icc_path, dest)
        log.info("Profile installed: %s", dest)
        return dest

    def sanity_check(self, icc_path: Path, log_output: str = "") -> list[str]:
        """Return list of warning strings; empty = pass."""
        issues: list[str] = []

        if not icc_path.exists():
            issues.append("Profile file not found.")
            return issues

        size = icc_path.stat().st_size
        if size < 1000:
            issues.append(f"Profile is suspiciously small ({size} bytes).")
        if size > 20_000_000:
            issues.append(f"Profile is very large ({size / 1e6:.1f} MB). Check quality setting.")

        combined = log_output or self._last_log
        for pattern, msg in [
            (r"Warning.*out of gamut",    "Out-of-gamut warnings in measurements."),
            (r"Profile creation failed", "colprof reported a failure."),
        ]:
            if re.search(pattern, combined, re.IGNORECASE):
                issues.append(msg)

        # Surface the structured warnings captured live during the run too.
        for _key, friendly in self._matched_warnings:
            if friendly and friendly not in issues:
                issues.append(friendly)

        return issues

    def expected_icc_path(self, params: ProfileParams) -> Path:
        # colprof APPENDS the ICC extension to the basename it is handed (the
        # same basename _build_args passes in). For a normal name that equals
        # base.with_suffix(ext); but when the basename itself still carries a
        # dotted token — e.g. a stray ".icm" left in the target name, giving a
        # "<name>.icm.ti3" measurement file — colprof writes "<name>.icm.icc",
        # whereas with_suffix() would instead look for "<name>.icc". Check the
        # literal appended form first so such a profile is still found, then the
        # legacy replace form for plain names.
        base = params.ti3_path.with_suffix("")
        candidates: list[Path] = []
        for ext in (".icc", ".icm"):
            candidates.append(Path(str(base) + ext))   # what colprof actually writes
            candidates.append(base.with_suffix(ext))   # legacy / extension-free names
        for candidate in candidates:
            if candidate.exists():
                return candidate
        return Path(str(base) + ".icc")

    # ------------------------------------------------------------------

    def _build_args(self, p: ProfileParams) -> list[str]:
        args: list[str] = []
        if p.verbose:
            args.append("-v")        # colprof prints progress + any error
        desc = p.description or p.ti3_path.stem
        args += ["-D", desc]
        args.append(f"-a{p.algorithm}")
        args.append(f"-q{p.quality}")
        if p.b2a_quality:
            args.append(f"-b{p.b2a_quality}")
        if abs(p.smoothing - 0.5) > 0.01:
            args += [f"-r{p.smoothing:.2f}"]
        if abs(p.dark_emphasis - 1.0) > 0.01:
            args += [f"-V{p.dark_emphasis:.1f}"]
        if p.gamut_src:
            args += ["-s", p.gamut_src]
        if p.k_rule:
            # -kz/-kh/-kx/-kr/-kp … (uppercase -K = locus variant); the five
            # curve values follow a "p" rule as separate arguments.
            args.append(("-K" if p.k_locus else "-k") + p.k_rule)
            if p.k_rule == "p":
                args += [f"{p.k_stle:g}", f"{p.k_stpo:g}", f"{p.k_enpo:g}",
                         f"{p.k_enle:g}", f"{p.k_shape:g}"]
        # Always stamp a manufacturer + model description so the profile is
        # self-identifying: colprof writes these as the 'dmnd'/'dmdd' device-ID
        # tags, which a device-link then copies into its profile-sequence ('pseq')
        # — otherwise that entry is left blank ("placeholder"). Falls back to
        # "ChromIQ" / the profile description when the caller hasn't set them.
        args += ["-A", p.manufacturer or "ChromIQ"]
        args += ["-M", p.model or desc]
        if p.copyright:
            args += ["-C", p.copyright]
        if p.illuminant:
            args += ["-i", p.illuminant]
        if p.observer:
            args += ["-o", p.observer]
        if p.src_viewing_cond:
            args.append(f"-c{p.src_viewing_cond}")
        if p.dst_viewing_cond:
            args.append(f"-d{p.dst_viewing_cond}")
        if p.fwa_enabled:
            args.append(f"-f{p.fwa_illum}" if p.fwa_illum else "-f")
        z_attrs = "".join(filter(None, [p.z_surface, p.z_media_type, p.z_polarity, p.z_color_mode]))
        if z_attrs:
            args += ["-Z", z_attrs]
        if p.z_default_intent:
            args += ["-Z", p.z_default_intent]
        if p.gamut_sat_src:
            args += ["-S", p.gamut_sat_src]
        if p.no_perc_gamut:
            args.append("-nP")
        if p.no_sat_gamut:
            args.append("-nS")
        if p.inv_gamut_map:
            args.append("-nI")
        if p.perc_intent:
            args.append(f"-t{p.perc_intent}")
        if p.sat_intent:
            args.append(f"-T{p.sat_intent}")
        if p.no_grid_pos:
            args.append("-np")
        if p.no_embedded_data:
            args.append("-nc")
        if p.no_input_shaper:
            args.append("-ni")
        if p.no_output_shaper:
            args.append("-no")
        # Input-profile white-point handling (-u / -ua / -uc / -u <scale>) and the
        # general primary clamp (-R). Mutually-exclusive -u modes (#121, Knut).
        if p.wp_mode == "u":
            args.append("-u")
        elif p.wp_mode == "ua":
            args.append("-ua")
        elif p.wp_mode == "uc":
            args.append("-uc")
        elif p.wp_mode == "scale" and p.wp_scale > 0:
            args += ["-u", f"{p.wp_scale:g}"]
        if p.clip_primaries:
            args.append("-R")
        if p.extra_args:
            args += shlex.split(p.extra_args)
        # Multi-ink charts (#72): the chart's TOTAL_INK_LIMIT rides the
        # .ti1 → .ti2 → .ti3 chain; prefill colprof's -l from it so the
        # finished profile never asks the printer for more ink than the chart
        # tested — unless the user already set -l/-L themselves. RGB
        # measurements never carry the keyword, so this is a no-op for them.
        if not any(a.startswith(("-l", "-L")) for a in args):
            limit = self._ti3_ink_limit(p.ti3_path)
            if limit is not None:
                args.append(f"-l{int(limit)}")
        # Base name without extension
        args.append(str(p.ti3_path.with_suffix("")))
        return args

    @staticmethod
    def _ti3_ink_limit(ti3_path: Path) -> float | None:
        """The measurement's ``TOTAL_INK_LIMIT`` (percent), or None (#72)."""
        try:
            text = Path(ti3_path).read_text(encoding="utf-8", errors="ignore")
        except OSError:
            return None
        m = re.search(r'^TOTAL_INK_LIMIT\s+"([\d.]+)"', text, re.MULTILINE)
        try:
            return float(m.group(1)) if m else None
        except ValueError:
            return None
