"""Which ``targen -d`` value makes a patch set with a given ``COLOR_REP``.

A patch set ChromIQ did not make with targen on screen (a built-in preset's
bundled ``.ti1``, a loaded one, an editor chart, a run's own patch set bound
again) says what inks it is for in its ``COLOR_REP`` keyword. Create Chart's
"Device Type" row has to say the same, or the panel shows CMYK while RGB
patches are laid out, and the "has the recipe changed?" snapshot is taken with
the wrong value in it (the CMYK/CR30 forum report, 2026-10-03).

THE TABLE IS GENERATED, NOT WRITTEN BY HAND. ``scripts/make_targen_device_
types.py`` runs ``targen -d0`` … ``targen -d15`` and records the ``COLOR_REP``
each one writes; ``tests/test_device_type_follows_the_patch_set.py`` runs
targen again and fails if Argyll ever answers differently. ``iRGB`` (print RGB,
``-d 2``) and ``RGB`` (video RGB, ``-d 3``) are different answers, and so are
the grey pair ``K``/``W``: the mapping is not one ink-letter rule.

A ``COLOR_REP`` that is not in the table (a set made with ``-D`` adding or
removing a colorant, or by another tool) has no ``-d`` that reproduces it, so
the caller leaves Device Type alone and logs it rather than guess.
"""
from __future__ import annotations

from pathlib import Path

# BEGIN GENERATED by scripts/make_targen_device_types.py (targen -d0..15)
TARGEN_DEVICE_TYPES: "dict[str, str]" = {
    "K": "0",
    "W": "1",
    "iRGB": "2",
    "RGB": "3",
    "CMYK": "4",
    "CMY": "5",
    "CMYKcm": "6",
    "CMYKcmk": "7",
    "CMYKRB": "8",
    "CMYKOG": "9",
    "CMYKRGB": "10",
    "CMYKOGV": "11",
    "CMYKOGB": "12",
    "CMYKcmk1k": "13",
    "CMYKOGcm": "14",
    "CMYKcm2c2m": "15",
}
# END GENERATED


def base_color_rep(color_rep: str) -> str:
    """The device half of a ``COLOR_REP``: ``CMYK_XYZ`` -> ``CMYK``.

    A ``.ti1``/``.ti2`` carries the device space alone; a ``.ti3`` appends the
    measurement space after an underscore."""
    return (color_rep or "").strip().strip('"').split("_", 1)[0]


def device_type_for(color_rep: str) -> "str | None":
    """The ``targen -d`` value that writes *color_rep*, or None."""
    return TARGEN_DEVICE_TYPES.get(base_color_rep(color_rep))


def color_rep_of(path: "Path | str") -> str:
    """The ``COLOR_REP`` a CGATS file declares, or "" when it declares none
    or cannot be read."""
    from workflow.printer_calibration import read_table
    try:
        _fields, _rows, kw = read_table(path)
    except (OSError, ValueError):
        return ""
    return kw.get("COLOR_REP", "").strip().strip('"')
