"""Create Chart's "Device Type" says what the bound patch set IS (beta 7).

THE REPORT (forum, ajaytanna, 2026-10-03, CMYK + CR30 + PrintFab). He picked a
CR30 preset, ticked "Edit patch recipe (override preset)", chose CMYK and a
CMYK printer calibration, and Generate answered "The chart could not be built
... set Device Type to CMYK" with Device Type already reading CMYK.

The CR30 presets, like every built-in, carry their own RGB patch set. Picking
one never touched -d, so a CMYK left on the panel stayed there beside 450 RGB
patches; the "has the recipe changed?" snapshot was taken WITH that CMYK in it,
so his Generate saw nothing changed, laid the RGB set out again, and the CMYK
calibration refused it. A run built that way stored -d 4 beside its RGB .ti1,
which set the same trap every time the run was selected again.

So every place a patch set is bound sets -d from the set's COLOR_REP, through
one helper (`TabChart._sync_device_type_to_bound_set`), right before the
snapshot, and clears the -D add/remove-colorant rows. The table it reads is
GENERATED by running targen -d0..15 (`scripts/make_targen_device_types.py`),
and the first test here runs targen again so the table cannot drift.

And when the calibration really does not fit the patch set, the refusal comes
before anything is built and names the box that is the way out
(M-PATCHSET-CAL-INKS).
"""
from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")

from core.resource_path import resource_path                    # noqa: E402
from workflow.targen_device_types import (TARGEN_DEVICE_TYPES,   # noqa: E402
                                          color_rep_of, device_type_for)

ROOT = Path(__file__).resolve().parent.parent
ARGYLL = Path(os.environ.get("CHROMIQ_ARGYLL_BIN", "/Applications/Argyll/bin"))


# --- 1. the table is targen's own answer ----------------------------------
@pytest.mark.skipif(not (ARGYLL / "targen").exists(),
                    reason="ArgyllCMS targen is not installed here")
def test_the_table_is_what_targen_writes_for_every_device_type():
    """Regenerated from targen itself. Hand-editing the table, or an Argyll
    that answers differently, turns this red."""
    r = subprocess.run(
        [sys.executable, str(ROOT / "scripts" / "make_targen_device_types.py"),
         "--argyll", str(ARGYLL), "--check"],
        capture_output=True, text=True, encoding="utf-8", timeout=300)
    assert r.returncode == 0, r.stdout + r.stderr


def test_the_table_covers_every_choice_the_panel_offers():
    import yaml
    params = yaml.safe_load((ROOT / "data" / "parameters.yaml").read_text(encoding="utf-8"))
    d = next(p for p in params["parameters"]["targen"] if p["flag"] == "-d")
    assert sorted(TARGEN_DEVICE_TYPES.values(), key=int) == d["choices"]


@pytest.mark.parametrize("rep,want", [
    ("iRGB", "2"), ("RGB", "3"), ("CMYK", "4"), ("CMYK_XYZ", "4"),
    ("K", "0"), ("W", "1"), ("CMYKOG", "9"), ("CMYKcm2c2m", "15"),
    ("CMYKO", None), ("", None), ("nonsense", None)])
def test_a_color_rep_maps_to_its_device_type_or_to_nothing(rep, want):
    assert device_type_for(rep) == want


def _every_bundled_patch_set() -> "list[Path]":
    """Every patch set a built-in preset binds. The stand-alone TC9.18 asset
    is not shipped in this tree (its preset is not offered), so it is taken
    only when present."""
    from ui.tabs.tab_chart import (KNUT_PRESETS, PREBUILT_PRESETS,
                                   TC918_TI1_ASSET)
    assets = {p.ti1_asset for p in KNUT_PRESETS} | {
        stem + ".ti1" for stem, _ in PREBUILT_PRESETS.values()}
    if resource_path(TC918_TI1_ASSET).is_file():
        assets.add(TC918_TI1_ASSET)
    return sorted(resource_path(a) for a in assets)


def test_every_built_in_patch_set_is_print_rgb_so_device_type_2():
    """CR30, TC9.18, ColorMunki/i1, Pharmacist, Knut, Scanner, Red River:
    every bundled set is iRGB, so every built-in pick must show -d 2."""
    sets = _every_bundled_patch_set()
    assert len(sets) > 20, sets
    for ti1 in sets:
        assert ti1.is_file(), ti1
        assert device_type_for(color_rep_of(ti1)) == "2", (ti1,
                                                            color_rep_of(ti1))


# --- 2. the tab ------------------------------------------------------------
@pytest.fixture(scope="module")
def qapp():
    from PyQt6.QtWidgets import QApplication
    return QApplication.instance() or QApplication([])


@pytest.fixture
def tab(qapp, tmp_path):
    from PyQt6.QtCore import QSettings
    from core.argyll_runner import ArgyllRunner
    from core.file_manager import FileManager
    from core.settings import AppSettings
    from ui.tabs.tab_chart import TabChart
    s = AppSettings()
    s._qs = QSettings(str(tmp_path / "s.ini"), QSettings.Format.IniFormat)
    s.set("custom_output_path", str(tmp_path / "projects"))
    t = TabChart(ArgyllRunner(s), FileManager(s), s)
    t._switch_mode("manual")
    yield t
    t.deleteLater()


def _leave_cmyk_and_a_colorant_on_the_panel(t) -> None:
    """The state the forum user left: CMYK, and one -D row in use."""
    t._set_manual_value("targen", "-d", "9")
    t._d_cascade_widgets[0].set_user_enabled(True)
    assert t._manual_value("targen", "-d") == "9"
    assert t._d_cascade_widgets[0].is_enabled_by_user


def _the_panel_says_print_rgb(t, sig) -> None:
    assert t._manual_value("targen", "-d") == "2"
    assert not any(w.is_enabled_by_user for w in t._d_cascade_widgets), (
        "an add/remove-colorant row was left on beside the preset's patch set")
    assert ("-d", "2", True) in sig or any(
        e[0] == "-d" and str(e[1]) == "2" for e in sig if len(e) == 3), sig


def _no_build(monkeypatch, calls: list):
    from ui.tabs.tab_chart import TabChart
    monkeypatch.setattr(TabChart, "_generate_from_ti1",
                        lambda self, ti1, *a, **k: calls.append(Path(ti1)) or True)


def _knut_family_representatives():
    """One preset per family the dropdown offers, by instrument and engine."""
    from ui.tabs.tab_chart import KNUT_PRESETS
    seen, out = set(), []
    for p in KNUT_PRESETS:
        # knut / pharmacist / redriver, by instrument and by engine kind
        fam = (p.ti1_asset.split("/")[2], p.instrument,
               p.layout_recipe is not None, p.engine)
        if fam not in seen:
            seen.add(fam)
            out.append(p)
    return out


@pytest.mark.parametrize("preset", _knut_family_representatives(),
                         ids=lambda p: p.slug)
def test_a_knut_family_preset_sets_print_rgb_and_clears_the_colorants(
        tab, monkeypatch, preset):
    calls: list = []
    _no_build(monkeypatch, calls)
    _leave_cmyk_and_a_colorant_on_the_panel(tab)
    tab._apply_knut_preset(preset.key, "Probe")
    _the_panel_says_print_rgb(tab, tab._knut_targen_sig)
    assert calls, "the preset was not built"


def test_the_tc918_preset_sets_print_rgb(tab, monkeypatch):
    from ui.tabs.tab_chart import TabChart
    calls: list = []
    _no_build(monkeypatch, calls)
    # The stand-alone TC9.18 asset is not in this tree; any bundled iRGB set
    # stands in for it, which is all the sync reads.
    stand_in = _every_bundled_patch_set()[0]
    monkeypatch.setattr(TabChart, "_tc918_ti1_path",
                        staticmethod(lambda: stand_in))
    _leave_cmyk_and_a_colorant_on_the_panel(tab)
    assert tab._apply_tc918_preset("Probe")
    _the_panel_says_print_rgb(tab, tab._tc918_targen_sig)


def test_a_prebuilt_files_preset_sets_print_rgb(tab, monkeypatch):
    """The prebuilt-files family (the older "by Pharmacist" bundles; the
    current Pharmacist charts are full-layout presets and are covered above).
    None is registered in this tree, so this runs when one is."""
    from ui.tabs.tab_chart import PREBUILT_PRESETS, TabChart
    if not PREBUILT_PRESETS:
        pytest.skip("no prebuilt-files preset is registered in this tree")
    key = next(iter(PREBUILT_PRESETS))
    monkeypatch.setattr(TabChart, "_name_needs_asking",
                        lambda self, *a, **k: False)
    monkeypatch.setattr(TabChart, "_gate_route_and_replace",
                        lambda self, *a, **k: (True, True))
    monkeypatch.setattr(TabChart, "_create_prebuilt_target",
                        lambda self, *a, **k: True)
    tab._builtin_ti1_path = resource_path(tab._builtin_ti1_asset(key))
    _leave_cmyk_and_a_colorant_on_the_panel(tab)
    assert tab._apply_prebuilt_preset(key, "Probe")
    _the_panel_says_print_rgb(tab, tab._prebuilt_targen_sig)


def _cmyk_ti1(path: Path) -> Path:
    path.write_text(
        'CTI1\n\nDESCRIPTOR "x"\nORIGINATOR "Argyll targen"\n'
        'COLOR_REP "CMYK"\n\nNUMBER_OF_FIELDS 8\nBEGIN_DATA_FORMAT\n'
        "SAMPLE_ID CMYK_C CMYK_M CMYK_Y CMYK_K XYZ_X XYZ_Y XYZ_Z\n"
        "END_DATA_FORMAT\n\nNUMBER_OF_SETS 2\nBEGIN_DATA\n"
        "1 0 0 0 0 95 100 108\n2 100 0 0 0 15 20 50\nEND_DATA\n",
        encoding="utf-8")
    return path


def test_a_loaded_cmyk_patch_set_sets_cmyk(tab, tmp_path):
    ti1 = _cmyk_ti1(tmp_path / "mine.ti1")
    tab._sync_device_type_to_bound_set(ti1)
    assert tab._manual_value("targen", "-d") == "4"


def test_a_colour_rep_no_device_type_makes_is_left_alone(tab, tmp_path):
    """A set made with -D (here CMYK + orange) has no -d that makes it.
    Device Type is not guessed."""
    ti1 = _cmyk_ti1(tmp_path / "odd.ti1")
    ti1.write_text(ti1.read_text(encoding="utf-8").replace('"CMYK"', '"CMYKO"'),
                   encoding="utf-8")
    tab._set_manual_value("targen", "-d", "3")
    tab._sync_device_type_to_bound_set(ti1)
    assert tab._manual_value("targen", "-d") == "3"


def test_the_run_rebind_tells_the_truth_about_a_run_that_stored_cmyk(
        tab, tmp_path):
    """A run built before beta 7 stores -d 4 beside its RGB .ti1 (the trap's
    footprint); selecting it binds the RGB set again, and -d follows it."""
    src = resource_path(_every_bundled_patch_set()[0].relative_to(
        resource_path("")).as_posix())
    ti1 = tmp_path / "run1" / "Probe.ti1"
    ti1.parent.mkdir()
    shutil.copy(src, ti1)
    tab._set_manual_value("targen", "-d", "4")
    tab._rebind_patch_set_from_run(ti1, given=True)
    assert tab._preset_ti1_path == ti1
    assert tab._manual_value("targen", "-d") == "2"
    assert any(e[0] == "-d" and str(e[1]) == "2"
               for e in tab._preset_ti1_targen_sig if len(e) == 3)


def test_every_snapshot_of_a_bound_set_is_taken_after_the_sync():
    """THE SOURCE: each assignment of a bound set's targen snapshot is
    preceded by the sync, within a few lines. A new bind path that forgets it
    turns this red."""
    import re
    src = (ROOT / "ui" / "tabs" / "tab_chart.py").read_text(encoding="utf-8")
    lines = src.splitlines()
    snaps = [i for i, ln in enumerate(lines) if re.search(
        r"_(tc918|knut|prebuilt|preset_ti1)_targen_sig = (\(|self\._targen_signature)",
        ln)]
    assert len(snaps) >= 6, snaps
    for i in snaps:
        window = "\n".join(lines[max(0, i - 12):i + 1])
        assert "_sync_device_type_to_bound_set" in window or "_sync(" in window, (
            f"tab_chart.py:{i + 1} snapshots a bound patch set without "
            "first setting Device Type from it")


# --- 3. the forum user's own route ------------------------------------------
def _cal(path: Path, rep: str = "CMYK") -> Path:
    ch = {"CMYK": "CMYK_C CMYK_M CMYK_Y CMYK_K",
          "RGB": "RGB_R RGB_G RGB_B"}[rep]
    n = len(ch.split())
    path.write_text(
        'CAL\n\nDESCRIPTOR "Argyll Device Calibration State"\n'
        'ORIGINATOR "Argyll printcal"\nDEVICE_CLASS "OUTPUT"\n'
        f'COLOR_REP "{rep}"\n\nNUMBER_OF_FIELDS {n + 1}\n'
        f"BEGIN_DATA_FORMAT\n{rep}_I {ch}\nEND_DATA_FORMAT\n\n"
        "NUMBER_OF_SETS 2\nBEGIN_DATA\n"
        f"0 {' '.join(['0'] * n)}\n1 {' '.join(['1'] * n)}\nEND_DATA\n",
        encoding="utf-8")
    return path


def _capture_info(monkeypatch) -> list:
    shown: list = []
    from ui import tooltip_button as W
    from ui.tabs import tab_chart as TC

    def fake_exec(self):
        shown.append((self.windowTitle(), getattr(self, "_body_text", "")))
        return 0
    real_init = W.InfoDialog.__init__

    def init(self, title, body, *a, **k):
        real_init(self, title, body, *a, **k)
        self._body_text = body
    monkeypatch.setattr(W.InfoDialog, "__init__", init)
    monkeypatch.setattr(W.InfoDialog, "exec", fake_exec)
    assert TC.InfoDialog is W.InfoDialog
    return shown


def _a_printtarg_preset():
    from ui.tabs.tab_chart import KNUT_PRESETS
    return next(p for p in KNUT_PRESETS if p.instrument == "CM")


def _set_cal(tab, cal: Path) -> None:
    """The calibration on both routes: printtarg's -K row and the layout
    panel's own group, which is what a seeded built-in lays out with."""
    tab._manual_cal_k_pw.set_value(str(cal))
    if not tab._manual_panel_inited:
        tab._init_manual_layout_panel()
    tab._manual_layout_panel.set_cal(str(cal), "apply")


def test_a_cmyk_calibration_refuses_the_rgb_preset_set_and_names_the_box(
        tab, tmp_path, monkeypatch):
    """The refusal comes BEFORE any build, names the preset and "Edit patch
    recipe (override preset)", and leaves the preset applied so that box is
    on screen to tick (#175 would otherwise put the whole tab back)."""
    from workflow import measurement_messages as M
    calls: list = []
    _no_build(monkeypatch, calls)
    shown = _capture_info(monkeypatch)
    _set_cal(tab, _cal(tmp_path / "printer.cal"))
    preset = _a_printtarg_preset()
    assert tab._apply_knut_preset(preset.key, "Probe") is True
    assert not calls, "the RGB patch set was laid out under a CMYK calibration"
    assert tab._knut_active, "the preset was put back; the box is gone"
    assert len(shown) == 1, shown
    title, body = shown[0]
    assert title == M.M_PATCHSET_CAL_INKS.render(
        source="x", chart_space="RGB", cal_space="CMYK")[0]
    assert "Edit patch recipe (override preset)" in body
    assert "CMYK" in body and "RGB" in body


def test_a_calibration_for_the_same_inks_is_not_refused(tab, tmp_path,
                                                        monkeypatch):
    calls: list = []
    _no_build(monkeypatch, calls)
    shown = _capture_info(monkeypatch)
    _set_cal(tab, _cal(tmp_path / "rgb.cal", "RGB"))
    assert tab._apply_knut_preset(_a_printtarg_preset().key, "Probe")
    assert calls and not shown


def test_the_printtarg_route_reads_the_k_row(tab, tmp_path, monkeypatch):
    """With the layout engine off and an instrument printtarg lays out, the
    calibration is the enabled -K / -I row."""
    shown = _capture_info(monkeypatch)
    tab._settings.set("use_chromiq_layout_engine", False)
    tab._set_manual_value("printtarg", "-i", "i1")
    assert not tab._manual_panel_lays_out()
    tab._manual_cal_k_pw.set_value(str(_cal(tmp_path / "k.cal")))
    assert tab._printer_cal_for_build() == tmp_path / "k.cal"
    ti1 = resource_path(_a_printtarg_preset().ti1_asset)
    assert tab._refuse_cal_inks_for_patch_set(ti1)
    assert shown and "Edit patch recipe (override preset)" in shown[0][1]


def test_the_engine_route_reads_the_panels_calibration(tab, tmp_path,
                                                       monkeypatch):
    """A CR30 preset is laid out by the engine, whose calibration is the
    layout panel's own (B8-1655), not the -K row."""
    from ui.tabs.tab_chart import KNUT_PRESETS
    calls: list = []
    _no_build(monkeypatch, calls)
    shown = _capture_info(monkeypatch)
    cr30 = next(p for p in KNUT_PRESETS if p.instrument == "CR30")
    tab._seed_knut_preset(cr30.key)
    tab._manual_layout_panel.set_cal(str(_cal(tmp_path / "p.cal")), "apply")
    assert tab._refuse_cal_inks_for_patch_set(resource_path(cr30.ti1_asset))
    assert shown and "Edit patch recipe (override preset)" in shown[0][1]


def test_the_live_preview_stops_without_a_window(tab, tmp_path, monkeypatch):
    shown = _capture_info(monkeypatch)
    _set_cal(tab, _cal(tmp_path / "printer.cal"))
    tab._seed_knut_preset(_a_printtarg_preset().key)
    ti1 = resource_path(_a_printtarg_preset().ti1_asset)
    assert tab._refuse_cal_inks_for_patch_set(ti1, preview=True)
    assert shown == []


def test_override_then_cmyk_then_generate_builds_a_fresh_cmyk_set(
        tab, monkeypatch):
    """The way out the message names: tick the box, choose CMYK, Generate.
    The snapshot now differs (it was taken at -d 2), so targen is asked."""
    calls: list = []
    _no_build(monkeypatch, calls)
    preset = _a_printtarg_preset()
    tab._set_manual_value("targen", "-d", "4")      # left from before
    tab._apply_knut_preset(preset.key, "Probe")       # re-pick: -d 2
    assert tab._manual_value("targen", "-d") == "2"
    calls.clear()
    tab._override_targen_check.setChecked(True)
    tab._set_manual_value("targen", "-d", "4")
    assert tab._targen_signature() != tab._knut_targen_sig
    assert tab._collect_manual().device_type == "4"


def test_repick_then_generate_unchanged_lays_out_the_rgb_set(tab,
                                                             monkeypatch):
    """The forum user's exact order without the calibration: the snapshot
    is -d 2 and so is the panel, so Generate reuses the preset's RGB set; it
    no longer believes it is building CMYK."""
    calls: list = []
    _no_build(monkeypatch, calls)
    preset = _a_printtarg_preset()
    tab._set_manual_value("targen", "-d", "4")
    tab._apply_knut_preset(preset.key, "Probe")
    assert tab._targen_signature() == tab._knut_targen_sig
    assert tab._manual_value("targen", "-d") == "2"


def test_the_targen_answer_binds_with_a_signature_that_knows_the_sync(
        tab, tmp_path):
    """Review of 036e28a2. The B8-1470 answer binds an older chart with the
    signature the panels had WHEN targen was asked, and the sync then moves
    -d. An i1Profiler import from before its iRGB fix says COLOR_REP "RGB"
    (-d 3) beside an RGB user's -d 2: the stale signature read as a targen
    edit, so ticking the override box and pressing Generate with nothing
    changed made a fresh patch set (#147). A change the person made while
    targen was asked must still count."""
    src = resource_path(_every_bundled_patch_set()[0].relative_to(
        resource_path("")).as_posix())
    ti1 = tmp_path / "run1" / "Old.ti1"
    ti1.parent.mkdir()
    ti1.write_text(Path(src).read_text(encoding="utf-8").replace(
        'COLOR_REP "iRGB"', 'COLOR_REP "RGB"'), encoding="utf-8")
    assert color_rep_of(ti1) == "RGB"
    assert tab._manual_value("targen", "-d") == "2"
    sig_asked = tab._targen_signature()
    tab._patch_set_question_answered(ti1, False, sig_asked)
    assert tab._preset_ti1_path == ti1
    assert tab._manual_value("targen", "-d") == "3"
    assert tab._targen_signature() == tab._preset_ti1_targen_sig, (
        "the bound set's snapshot disagrees with the panel the sync left")

    # A real edit made while targen was being asked is not washed out.
    tab._preset_ti1_path = None
    tab._set_manual_value("targen", "-d", "2")
    sig_asked = tab._targen_signature()
    for pw in tab._manual_widgets["targen"]:
        if pw.flag == "-f":
            pw.set_value(int(pw.get_raw_value() or 0) + 7)
            pw.set_user_enabled(True)
            break
    else:
        pytest.skip("no -f row on this panel")
    tab._patch_set_question_answered(ti1, False, sig_asked)
    assert tab._targen_signature() != tab._preset_ti1_targen_sig


def test_guided_lays_out_without_a_calibration_so_nothing_is_refused(
        tab, tmp_path, monkeypatch):
    """Review of 036e28a2. Guided hands the creator no printer calibration at
    all (`_collect_guided`), so a CMYK .cal left on Manual's hidden panel
    must not refuse an RGB patch set laid out in Guided, with a window that
    names a box Guided does not show."""
    shown = _capture_info(monkeypatch)
    _set_cal(tab, _cal(tmp_path / "printer.cal"))
    ti1 = resource_path(_a_printtarg_preset().ti1_asset)
    tab._switch_mode("guided")
    assert tab._current_mode() == "guided"
    p = tab._collect_params()
    assert not p.engine_cal_path
    assert not any(a.startswith(("-K", "-I"))
                   for a in (p.extra_printtarg_args or "").split())
    assert tab._printer_cal_for_build() is None
    assert not tab._refuse_cal_inks_for_patch_set(ti1)
    assert shown == []
    tab._switch_mode("manual")
    assert tab._printer_cal_for_build() is not None
