r"""The driver install writes a certificate to the machine. The window says so.

MEASURED READ-ONLY ON THE ARM64 BENCH, 2026-09-06. `Install Driver` at 06:43:28
produced `CN=USB\VID_0765&PID_6008 (libwdi autogenerated)` in BOTH
`Cert:\LocalMachine\Root` and `…\TrustedPublisher`, `NotBefore` 06:43:31 — three
seconds later, and five minutes after the only other driver install that
evening. `core/usb_driver_installer.py` carries the full evidence beside
`WDI_DRIVER_TYPE`, including why no option of wdi-simple's can turn it off.

The window used to say nothing about it. These are the guards that keep it
saying something, and each one is here because leaving it out would let a
specific, named failure back in:

* the paragraph appears BEFORE the click, not only behind a button;
* it carries the three load-bearing facts (which lists, whose computer, that it
  stays behind) rather than deferring all of them;
* the button and the paragraph appear together, in every hardware shape;
* the Zadig branch gets the disclosure too, because Zadig is libwdi;
* and nothing in the extensive text claims more than was measured — in
  particular that the certificate is unrestricted, which is FALSE (its Extended
  Key Usage is critical and is Code Signing alone), and that removing it later
  is safe, which is UNTESTED.
"""
from __future__ import annotations

import re
from types import SimpleNamespace

import pytest

from ui.dialogs import settings_dialog as sd

ALL_CODES = ["de", "es", "fr", "it", "ja", "nl", "no", "pl", "pt", "ru", "sv",
             "zh_CN"]

#: How many `tr()` keys `_english_keys()` must recover. Seven of the feature's
#: eight; the notice window's TITLE is written at the call site and is checked
#: by `test_the_notice_title_is_a_key_too`.
EXPECTED_SWEPT_KEYS = 7


def dev(name: str, has_winusb: bool):
    return SimpleNamespace(name=name, has_winusb=has_winusb)


I1PRO = "GretagMacbeth i1 Pro / i1 Pro 2"
SPYDER = "Datacolor SpyderX"

#: Every shape of the USB half, and whether a driver is about to be installed
#: for anything in it. The pairing of the paragraph and the button is asserted
#: over ALL of them rather than over the one that was in mind while writing it.
SHAPES = [
    ([], True, False),
    ([], False, False),
    ([dev(I1PRO, False)], True, True),
    ([dev(I1PRO, False)], False, True),
    # ALREADY DRIVEN IS **TRUE**, AND IT WAS FALSE HERE UNTIL A REVIEW.
    # `Reinstall Driver` runs `install_winusb` over every detected device
    # (`targets = needs_install or devices`), and libwdi mints a fresh
    # certificate every run. The repair path writes to the root store too.
    ([dev(I1PRO, True)], True, True),
    ([dev(I1PRO, True)], False, True),
    ([dev(I1PRO, True), dev(SPYDER, True)], True, True),
    ([dev(I1PRO, False), dev(SPYDER, False)], True, True),
    ([dev(I1PRO, True), dev(SPYDER, False)], True, True),
    ([dev(I1PRO, False), dev(SPYDER, True)], False, True),
]


# ---------------------------------------------------------------------------
# 1. It is said before the click
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("devices,wdi,expected", SHAPES)
def test_the_paragraph_and_the_button_always_appear_together(
        devices, wdi, expected):
    """Neither half means anything alone.

    A paragraph that says "click <b>What this changes…</b>" beside a window with
    no such button sends the user hunting for a control that is not there; a
    button beside a paragraph that never mentions a certificate explains
    something nobody was told about. `usb_shows_certificate_details` is what
    `_show_usb_installer` builds the button from, so this ties the two to one
    another over every hardware shape instead of trusting them to stay equal.
    """
    msg, _ = sd.usb_installer_text(devices, wdi_available=wdi)
    in_text = sd.usb_certificate_notice_line() in msg
    assert sd.usb_shows_certificate_details(devices, wdi) is expected
    assert in_text is expected, (devices, wdi)


def test_the_disclosure_is_in_the_first_window_not_only_behind_the_button():
    """The whole placement decision, as an assertion.

    If this ever fails because somebody moved the paragraph into
    `usb_certificate_details_text()` to shorten the window, the disclosure has
    become a footnote: a user who presses Install Driver without opening
    anything else would then have been told nothing.
    """
    msg, _ = sd.usb_installer_text([dev(I1PRO, False)], wdi_available=True)
    assert "certificate" in msg


@pytest.mark.parametrize("phrase", [
    # which lists it goes into
    "lists of trusted signers",
    # …and that one of them is THE ROOT STORE. This phrase was missing while
    # the docstring above claimed it was there: the paragraph said "two of
    # Windows' own lists of trusted signers", which is materially less than
    # naming the list Windows uses to decide which authorities to believe.
    "trusted-root list",
    # whose computer trusts it
    "for the whole computer",
    # and that it does not go away with the driver
    "It stays there after the driver is gone",
])
def test_the_three_load_bearing_facts_are_before_the_click(phrase):
    """The first draft deferred all three to the details window.

    It said only that "a small security certificate" is added to "your
    computer's list of trusted certificates" — which never says *root*, never
    says the whole machine trusts it, and never says it stays behind. Those
    three ARE the disclosure. Everything else may live behind the button.
    """
    msg, _ = sd.usb_installer_text([dev(I1PRO, False)], wdi_available=True)
    assert phrase in msg, phrase


def test_the_zadig_branch_is_disclosed_too_because_zadig_is_libwdi():
    """The hole the first draft left, named.

    Without the bundled wdi-simple this window installs nothing — it sends the
    user to Zadig, and Zadig is libwdi's own front end; libwdi's Certification
    Practice Statement names it first among the applications that install these
    certificates. Keying the disclosure on `wdi_available` would have told
    exactly the users ChromIQ installs for, and none of the users it sends
    elsewhere.
    """
    msg, btn = sd.usb_installer_text([dev(I1PRO, False)], wdi_available=False)
    assert btn == "Open Zadig"
    assert sd.usb_certificate_notice_line() in msg


def test_the_repair_path_discloses_too_because_it_reinstalls_the_certificate():
    """THIS TEST USED TO ASSERT THE OPPOSITE, ON A FALSE PREMISE.

    It was called `…does_not_reach_a_user_who_is_installing_nothing` and its
    docstring said that with every device already driven "nothing is about to
    be written". That is not true. `_show_usb_installer` computes
    ``targets = needs_install or devices``, so `Reinstall Driver` runs
    `install_winusb` over every detected device, and libwdi mints a **fresh**
    certificate on every run — the details text says so itself two paragraphs
    later. The repair path was the one branch with no disclosure at all, and
    its user is the one with no driver problem to justify the risk.

    A guard asserting a comfortable falsehood is worse than no guard, because
    it stops anybody looking.
    """
    for wdi in (True, False):
        msg, btn = sd.usb_installer_text([dev(I1PRO, True)], wdi_available=wdi)
        assert btn in ("Reinstall Driver", "Open Zadig"), btn
        assert sd.usb_certificate_notice_line() in msg


def test_a_window_with_no_instrument_has_nothing_to_disclose():
    """The one shape that really is silent — and it is silent because there is
    no button on it at all, not because a certificate is not written."""
    for wdi in (True, False):
        msg, btn = sd.usb_installer_text([], wdi_available=wdi)
        assert btn is None
        assert "certificate" not in msg


# ---------------------------------------------------------------------------
# 2. Nothing in it claims more than was measured
# ---------------------------------------------------------------------------

def _all_text() -> str:
    return sd.usb_certificate_notice_line() + sd.usb_certificate_details_text()


def test_it_never_says_the_certificate_is_trusted_for_everything():
    """THE ONE MEASURABLY FALSE CLAIM, AND IT WAS WRITTEN ONCE ALREADY.

    A draft said "a certificate in the Trusted Root list is trusted for
    everything, not only for drivers". It is not. Extension 2.5.29.37 on the
    certificate on this bench is marked CRITICAL and contains exactly one
    purpose — Code Signing, 1.3.6.1.5.5.7.3.3 — which Windows must honour, so it
    cannot vouch for a web site, an e-mail or a client identity. libwdi's
    `pki.c:723,749` agrees.

    That draft was wrong in the SCARY direction, inside a change whose whole
    subject is telling the truth about the install. It would have read, to a
    photographer mid-repair, as a root-CA compromise.
    """
    text = _all_text().lower()
    for claim in ("trusted for everything",
                  "for anything at all",
                  "trusted for any purpose"):
        assert claim not in text, claim
    # …and the limit is stated, not merely not-denied.
    assert "cannot vouch for a website" in sd.usb_certificate_details_text()


def test_the_removal_advice_is_hedged_because_the_experiment_was_not_run():
    """Deleting the certificate and rebooting was NOT tested.

    Two things point the same way — `libusb0.sys` carries its own signatures
    from Microsoft and from its authors, and two driver packages on the bench
    whose certificates libwdi had already deleted are still enumerated — but
    "enumerated" is not "starts after a reboot", and the exact experiment would
    have meant modifying a certificate store on a working bench. So the window
    says what is expected, and says that it is only what is expected.
    """
    text = sd.usb_certificate_details_text()
    assert "we can tell you what we expect" in text
    assert "not that we have proved it" in text
    assert "was not tested" in text


def test_it_does_not_promise_a_repair_nobody_has_produced():
    """"Running Install Driver again puts everything back" was a repair promise
    for a failure mode nobody has ever produced. What is known is only that a
    second install mints a fresh certificate and reinstalls the driver.

    The positive assertion comes first, because a bare `not in` passes on an
    empty string and this test would then be guarding nothing at all.
    """
    text = _all_text()
    assert "installs the driver, and its certificate, from the start" in text
    assert "puts everything back" not in text


def test_the_replacement_claim_is_scoped_to_one_instrument():
    """libwdi deletes the certificate with the SAME SUBJECT, and the subject is
    the hardware ID — so it is one certificate per instrument, not one per
    machine. This bench holds two. And `_show_usb_installer` runs the install
    over every unbound instrument, so one click by a two-instrument owner
    creates two."""
    text = sd.usb_certificate_details_text()
    assert "for the same instrument" in text
    assert "a different instrument gets its own" in text


def test_the_scope_of_the_measurement_is_stated():
    """ARM64, `--type 1`, one instrument. Not "Windows"."""
    text = sd.usb_certificate_details_text()
    assert "ARM64" in text
    assert "one machine is what was checked" in text


def test_the_argyll_comparison_is_the_measured_one():
    """`ArgyllCMS_install_USB.exe` is itself a libwdi program — it carries
    `wdi_prepare_driver`, `CreateSelfSignedCert`, `CN=%s (libwdi
    autogenerated)` and the literal `Added certificate '%s' to 'Root' and
    'TrustedPublisher' stores` — and `CN=ArgyllCMS (libwdi autogenerated)` is in
    both stores on this bench, from 2026-05-08. The window may say so because it
    was measured, not because it sounds reassuring."""
    text = sd.usb_certificate_details_text()
    assert "ArgyllCMS (libwdi autogenerated)" in text
    assert "ArgyllCMS's own USB driver installer does exactly this" in text


def test_it_tells_the_user_how_to_look_and_how_to_remove():
    """The owner asked for both, in concrete steps."""
    text = sd.usb_certificate_details_text()
    assert "certlm.msc" in text
    assert "Trusted Root Certification Authorities" in text
    assert "Trusted Publishers" in text
    assert "right-click the certificate" in text


def test_the_search_term_it_gives_survives_the_path_wrapper():
    r"""`_driver_notice` runs its text through `_let_paths_wrap`, which inserts
    U+200B after every backslash. A user told to search for
    `USB\VID_0765&PID_6008 (libwdi autogenerated)` would copy an invisible
    character into certlm's find box and match nothing. The tail it actually
    names has no backslash — and no ampersand, which is the other way a rich
    text window eats a name."""
    text = sd.usb_certificate_details_text()
    assert "(libwdi autogenerated)" in text
    assert "\\" not in text
    assert not re.search(r"&(?!amp;|nbsp;|lt;|gt;)", text)


# ---------------------------------------------------------------------------
# 3. It renders — in twelve languages
# ---------------------------------------------------------------------------

def _assert_rich_text_is_sane(text: str, where: str) -> None:
    for tag in ("b", "i"):
        assert text.count(f"<{tag}>") == text.count(f"</{tag}>"), \
            f"{where}: unbalanced <{tag}>"
    assert not set(re.findall(r"<\s*/?\s*([a-zA-Z]+)", text)) - {
        "b", "i", "br"}, f"{where}: a tag that is not b/i/br"
    assert not re.search(r"&(?!amp;|nbsp;|lt;|gt;)", text), \
        f"{where}: a bare ampersand"


def test_the_rich_text_is_balanced():
    """Every tag opened is closed. A stray `<` swallows everything up to the
    next `>` SILENTLY — measured on this Qt: `'5 < 6 and 7 > 2'` renders as
    `'5 2'`."""
    _assert_rich_text_is_sane(sd.usb_certificate_notice_line(), "notice line")
    _assert_rich_text_is_sane(sd.usb_certificate_details_text(), "details")


@pytest.mark.parametrize("code", ALL_CODES)
def test_the_rich_text_survives_translation(code):
    """AND THE ENGLISH CHECK ABOVE DOES NOT COVER THIS, WHICH IS THE WHOLE
    POINT OF IT.

    The risk named in the sibling test is "twelve translators writing free
    prose into a rich-text key" — and the sibling test reads the functions,
    which return ENGLISH under the suite's default language. It could not
    fail on a translation if it tried. Nothing in `tests/test_i18n.py` checks
    tag balance either. This reads the catalogues.
    """
    import json
    from pathlib import Path

    root = Path(sd.__file__).resolve().parent.parent.parent / "data" / "i18n"
    cat = json.loads(root.joinpath(f"{code}.json").read_text(encoding="utf-8"))
    for key in _english_keys():
        if key in cat:
            _assert_rich_text_is_sane(cat[key], f"[{code}] {key[:40]}…")


@pytest.mark.parametrize("code", ALL_CODES)
def test_every_language_has_the_disclosure_and_it_is_not_english(code):
    """A missing key falls back to English silently — which for THIS text means
    a German user is shown an English page about their own root certificate
    store. `test_i18n.py` catches the missing key; this catches the identity
    mapping that satisfies it without translating anything."""
    import json
    from pathlib import Path

    root = Path(sd.__file__).resolve().parent.parent.parent / "data" / "i18n"
    cat = json.loads(root.joinpath(f"{code}.json").read_text(encoding="utf-8"))
    keys = _english_keys()
    # NOT JUST "non-empty". The sweep is a regex over `inspect.getsource`, so a
    # single-quoted literal, an f-string, a `+` inside the call or a comment
    # between the parens drops a key SILENTLY — and one surviving key satisfies
    # a truthiness check. The count is the thing that has to be deliberate:
    # adding a sixth paragraph should make this line fail and be bumped.
    assert len(keys) == EXPECTED_SWEPT_KEYS, (
        f"the sweep recovered {len(keys)} keys, expected "
        f"{EXPECTED_SWEPT_KEYS} — either a paragraph was added (bump the "
        f"number) or the regex stopped seeing one: {[k[:40] for k in keys]}")
    for key in keys:
        assert key in cat, f"[{code}] missing: {key[:60]}…"
        assert cat[key] != key, (
            f"[{code}] left as English: {key[:60]}…")


def _english_keys() -> "list[str]":
    """The English source strings this feature adds, read out of the source.

    Selecting them by `inspect.getsource` rather than listing them by hand is
    what keeps the sweep from going blind when a sixth paragraph is added: a new
    `tr()` in these functions joins the sweep without anybody remembering to.
    """
    import inspect

    src = (inspect.getsource(sd.usb_certificate_notice_line)
           + inspect.getsource(sd.usb_certificate_details_text)
           + inspect.getsource(sd._label_what_this_changes))
    # Reconstruct each tr("…" "…") argument: implicitly concatenated literals.
    out = []
    for call in re.finditer(r'tr\(\s*((?:"(?:[^"\\]|\\.)*"\s*)+)\)', src,
                            re.S):
        parts = re.findall(r'"((?:[^"\\]|\\.)*)"', call.group(1))
        out.append("".join(parts).replace('\\"', '"').replace("\\\\", "\\"))
    return out


def test_the_notice_title_is_a_key_too():
    """The window's TITLE is user-facing and is the one string a `tr()` sweep
    over the text functions cannot see — it is written at the call site in
    `_show_usb_installer`."""
    import inspect
    import json
    from pathlib import Path

    src = inspect.getsource(sd.SettingsDialog._show_usb_installer)
    title = "What installing the driver changes"
    assert f'tr("{title}")' in src
    root = Path(sd.__file__).resolve().parent.parent.parent / "data" / "i18n"
    for code in ALL_CODES:
        cat = json.loads(root.joinpath(f"{code}.json").read_text(
            encoding="utf-8"))
        assert title in cat, f"[{code}] the notice title is not a key"
        assert cat[title] != title, f"[{code}] the notice title is English"
