"""Render-derived scan geometry (workflow.layout_from_render).

Charts without creation-time geometry — the prebuilt "by Pharmacist" bundles
and printtarg charts whose ``-s`` capture is discarded (ColorMunki double
density at -a0.91–0.93, #108) — get their exact patch grid derived from the
rendered TIFF, colour-verified patch by patch against the ``.ti2``
(correct-or-absent)."""
import json
import shutil
import subprocess
from pathlib import Path

import pytest

pytest.importorskip("PyQt6")
from PyQt6.QtWidgets import QApplication  # noqa: E402

from tests.argyll_env import argyll_tool  # noqa: E402
from workflow.layout_from_render import (RenderGeometryError,  # noqa: E402
                                         derive_layout_from_render)

ASSETS = Path(__file__).resolve().parent.parent / "assets/charts/pharmacist"
ARGYLL_TARGEN = argyll_tool("targen")


@pytest.fixture(scope="module")
def qapp():
    return QApplication.instance() or QApplication([])


@pytest.fixture(scope="module")
def engine_chart(qapp, tmp_path_factory):
    """A small real engine chart (in-process build, no Argyll binaries needed
    beyond targen for the patch set) with its exact geometry sidecar."""
    if ARGYLL_TARGEN is None:
        pytest.skip("Argyll targen not installed")
    d = tmp_path_factory.mktemp("render")
    subprocess.run([str(ARGYLL_TARGEN), "-d2", "-f60", str(d / "t")],
                   check=True, capture_output=True)
    from workflow.layout_engine.chart import build_chart
    res = build_chart(d / "t.ti1", d / "t", instrument="i1", paper="A4",
                      dpi=150, randomize=True, seed=7)
    return d, res


def test_derive_matches_engine_geometry(engine_chart):
    """Deriving from an engine chart's render reproduces the engine's own
    exact patch rects — same locs, positions within 2 px."""
    d, res = engine_chart
    lay = derive_layout_from_render(sorted(d.glob("t_*.tif")) or [d / "t.tif"],
                                    d / "t.ti2")
    assert lay["engine"] == "derived"
    exact = {p["loc"]: p for p in res.patch_rects_px} \
        if hasattr(res, "patch_rects_px") else None
    derived = {p["loc"]: p for p in lay["patches"]}
    # locs must cover the .ti2 exactly
    from workflow.ti3_analysis import parse_ti3
    assert set(derived) == set(parse_ti3(d / "t.ti2").sample_locs)
    if exact:  # engine result exposes its rects → compare positions
        for loc, p in derived.items():
            e = exact[loc]
            assert abs(p["x"] - e["x"]) <= 2 and abs(p["y"] - e["y"]) <= 2
    # strips block for the measure-tab overlay
    assert lay["strips"] and all(
        {"page", "x", "y", "w", "h"} <= set(s) for s in lay["strips"])


def test_derive_refuses_wrong_reference(engine_chart, tmp_path):
    """A .ti2 whose colours don't match the render (two patches swapped) is
    refused — never a silently wrong geometry."""
    d, _res = engine_chart
    text = (d / "t.ti2").read_text(encoding="utf-8").splitlines()
    # swap the RGB fields of the two most DIFFERENT data rows (swapping two
    # similar colours would legitimately still validate)
    data_at = next(i for i, ln in enumerate(text) if ln.strip() == "BEGIN_DATA")
    rows = [i for i in range(data_at + 1, len(text)) if text[i].strip()
            and not text[i].startswith("END_DATA")]
    def rgb(i):
        return [float(v) for v in text[i].split()[2:5]]
    i0 = rows[0]
    i1 = max(rows[1:], key=lambda i: sum(abs(a - b) for a, b
                                         in zip(rgb(i), rgb(i0))))
    a, b = text[i0].split(), text[i1].split()
    a[2:5], b[2:5] = b[2:5], a[2:5]
    text[i0], text[i1] = " ".join(a), " ".join(b)
    bad = tmp_path / "bad.ti2"
    bad.write_text("\n".join(text), encoding="utf-8")
    with pytest.raises(RenderGeometryError):
        derive_layout_from_render(
            sorted(d.glob("t_*.tif")) or [d / "t.tif"], bad)


@pytest.mark.parametrize("leaf", [
    "rgb/colormunki/a4/tc300", "rgb/i1pro/a4/abw1110",
])
def test_prebuilt_bundles_carry_verified_geometry(leaf):
    """The bundled prebuilt charts ship a derived channels.json the scanner
    target accepts (generated by scripts/derive_prebuilt_geometry.py)."""
    d = ASSETS / leaf
    stem = next(d.glob("*.ti2")).stem
    sidecar = d / f"{stem}.channels.json"
    assert sidecar.is_file(), "run scripts/derive_prebuilt_geometry.py"
    from workflow.scanin_target import has_scanner_geometry
    assert has_scanner_geometry(sidecar)
    lay = json.loads(sidecar.read_text(encoding="utf-8"))["layout"]
    from workflow.ti3_analysis import parse_ti3
    assert {p["loc"] for p in lay["patches"]} == \
        set(parse_ti3(d / f"{stem}.ti2").sample_locs)


def test_scanin_target_builds_from_derived(tmp_path):
    """The scanner-target worker consumes a derived layout end-to-end
    (per-page .cht + .cie from the .ti2 aim values as reference)."""
    d = ASSETS / "rgb/colormunki/a4/abw702"     # 2-page bundle
    sidecar = d / "abw702.channels.json"
    assert sidecar.is_file(), "run scripts/derive_prebuilt_geometry.py"
    from workflow.scanin_target import build_scanin_target_from_paths
    res = build_scanin_target_from_paths(sidecar, d / "abw702.ti2",
                                         tmp_path / "abw702")
    assert res.n_pages == 2 and res.n_patches == 702
    assert all(p.is_file() for p in res.cht_paths)
    assert res.cie_path.is_file()


def test_capture_fallback_derives_from_render(engine_chart, tmp_path):
    """ChartCreator's fallback stores a derived layout when the printtarg -s
    capture is impossible (Basti's CM double-density repro)."""
    d, _res = engine_chart
    work = tmp_path / "run"
    work.mkdir()
    for f in list(d.glob("t.*")) + list(d.glob("t_*.tif")):
        shutil.copy(f, work / f.name)
    (work / "t.channels.json").unlink(missing_ok=True)
    from workflow.chart_creator import ChartCreator
    creator = ChartCreator.__new__(ChartCreator)   # fallback needs no deps
    creator._derive_geometry_from_render(work, "t")
    doc = json.loads((work / "t.channels.json").read_text(encoding="utf-8"))
    assert doc["layout"]["engine"] == "derived"
    from workflow.scanin_target import has_scanner_geometry
    assert has_scanner_geometry(work / "t.channels.json")
