"""The photograph path: a camera's file, and the fit that makes its grid usable.

Two things ship here and this file guards both, plus the one property the
whole design rests on.

1. ``as_tiff`` — ArgyllCMS reads TIFF and a camera writes JPEG, so a photograph
   must be converted before ``scanin`` sees it. **A file that is already a TIFF
   must come back untouched**, because that is the flatbed path.
2. ``refine_corners`` — the four corners the user placed, nudged onto the
   chart's own patches. Measured on Knut's Wolf Faust scan through a 48-cell
   bow x lens x tilt matrix: a 5.5 % bow alone and a 15-degree compound tilt
   alone each cost nothing, and the two together put 102 patches over 1 dE00.
3. **The clamp.** A grid slipped a WHOLE patch pitch reads every patch as its
   neighbour and is, to any measure taken inside the boxes, exactly as good as
   the right answer. Nothing computed from the pixels can separate the two —
   only distance can. So the tests that matter most here are the ones that pin
   the bound, not the ones that pin the accuracy.
"""
from __future__ import annotations

import os
from pathlib import Path

import pytest

os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")

from core.text_io import read_text                              # noqa: E402
from workflow import photo_fit                                  # noqa: E402
from workflow.cht_parser import parse_cht                       # noqa: E402
from workflow.photo_fit import (CLAMP_PITCHES, as_tiff,         # noqa: E402
                                patch_pitch_px, refine_corners)
from workflow.standard_targets import (demo_scan_layout,        # noqa: E402
                                       make_test_scan)

CHT = Path("/Applications/Argyll/ref/ColorChecker.cht")
pytestmark = pytest.mark.skipif(not CHT.is_file(),
                                reason="ArgyllCMS ref/ChartChecker.cht not installed")


@pytest.fixture(scope="module")
def demo(tmp_path_factory):
    """The app's OWN demo scan of a real target — a known image with a known
    truth, generated by the code that ships, so nothing here re-derives the
    geometry it is testing."""
    d = tmp_path_factory.mktemp("photo-fit")
    tif, _cie = make_test_scan(CHT, d)
    text = read_text(CHT, lenient=True)
    boxes = parse_cht(text).patches
    _sc, px0, py0, pw, ph, _W, _H, _sr, _sh = demo_scan_layout(text, boxes)
    truth = [(px0, py0), (px0 + pw, py0), (px0 + pw, py0 + ph), (px0, py0 + ph)]
    bbox = (min(b.x1 for b in boxes), min(b.y1 for b in boxes),
            max(b.x2 for b in boxes), max(b.y2 for b in boxes))
    pitch = patch_pitch_px(boxes, truth, bbox)
    return tif, boxes, truth, pitch


def _shift(quad, dx, dy):
    return [(x + dx, y + dy) for x, y in quad]


def _worst(a, b):
    import math
    return max(math.dist(p, q) for p, q in zip(a, b))


# ---------------------------------------------------------------- as_tiff
def test_a_tiff_is_handed_back_untouched(tmp_path, demo):
    """THE FLATBED PATH. A scan is not copied, not re-encoded, not even opened —
    the very same path comes back, and the bytes on disk are unchanged."""
    tif, _b, _t, _p = demo
    before = Path(tif).read_bytes()
    stat_before = Path(tif).stat().st_mtime_ns
    out, converted = as_tiff(tif, tmp_path)
    assert converted is False
    assert Path(out) == Path(tif)
    assert Path(tif).read_bytes() == before
    assert Path(tif).stat().st_mtime_ns == stat_before
    assert not list(tmp_path.iterdir()), "a scan must leave nothing behind"


def test_a_photograph_is_converted_and_keeps_its_pixels(tmp_path, demo):
    from PIL import Image
    tif, _b, _t, _p = demo
    jpg = tmp_path / "photo.jpg"
    with Image.open(tif) as im:
        im.convert("RGB").save(jpg, quality=100, subsampling=0)
    out, converted = as_tiff(jpg, tmp_path / "work")
    assert converted is True
    assert Path(out).suffix.lower() in photo_fit.TIFF_SUFFIXES
    with Image.open(out) as a, Image.open(jpg) as b:
        assert a.size == b.size
        # `tobytes()` rather than `getdata()`: the latter is deprecated and
        # goes away in Pillow 14 (2027-10-15), and it compares the same
        # pixels either way. A test that warns today is a test that fails
        # on a dependency bump nobody connected to this file.
        assert a.convert("RGB").tobytes() == b.convert("RGB").tobytes()


def test_the_pitch_is_the_patch_pitch_on_a_two_block_chart():
    """A REGRESSION WITH A NAME. ``it8.cht`` lays its main grid at
    x = 26.625 + 25.625·i and its greyscale strip at x = 25.625·j, so the sorted
    union of patch origins contains 25.625 AND 26.625 — one unit apart. Taking
    the pitch as "the smallest step between origins" therefore returned 1.0
    instead of 25.625, the clamp came out two pixels wide, and the fit refused
    every real IT8 photograph with "the grid is too far from the patches".
    It was found by driving the real window; this is the unit that keeps it."""
    for cht, want in (("it8.cht", 25.625),
                      ("it8Wolf.cht", 25.625),
                      ("ColorCheckerHalfPassport.cht", 15.0)):
        path = CHT.parent / cht
        if not path.is_file():
            continue
        boxes = parse_cht(read_text(path, lenient=True)).patches
        bbox = (min(b.x1 for b in boxes), min(b.y1 for b in boxes),
                max(b.x2 for b in boxes), max(b.y2 for b in boxes))
        unit_quad = [(bbox[0], bbox[1]), (bbox[2], bbox[1]),
                     (bbox[2], bbox[3]), (bbox[0], bbox[3])]
        got = patch_pitch_px(boxes, unit_quad, bbox)
        assert abs(got - want) < 0.75, f"{cht}: pitch {got}, expected ~{want}"


# ------------------------------------------------------------ the fit works
#: How far a placement may be from the truth before the READ changes, in patch
#: pitches. Measured on Knut's own Wolf Faust and LaserSoft scans through the
#: real ``scanin -F`` (beta 8, agent F): at 0.113 pitch — where the sample box
#: first crosses a patch border — **zero** patches move by 1 dE00, and the read
#: only starts to go at about 0.25. So this, and not "the corners land on the
#: exact truth", is what the fit has to achieve; the objective has a flat basin
#: inside which every box is on its own patch and the read is identical.
READ_TOLERANCE_PITCHES = 0.25


def test_a_misplaced_grid_is_pulled_back_onto_the_patches(demo):
    tif, boxes, truth, pitch = demo
    off = _shift(truth, 0.3 * pitch, -0.25 * pitch)
    assert _worst(off, truth) > READ_TOLERANCE_PITCHES * pitch, \
        "the fixture must start OUTSIDE the tolerance or it proves nothing"
    res = refine_corners(tif, boxes, off)
    assert res.ok, res.reason
    after = _worst(res.corners, truth)
    assert after < _worst(off, truth)
    assert after <= READ_TOLERANCE_PITCHES * pitch, (
        f"the fit left the grid {after / pitch:.3f} pitches out, and the read "
        f"changes past {READ_TOLERANCE_PITCHES}")


def test_a_placement_that_is_already_right_is_left_alone(demo):
    tif, boxes, truth, _p = demo
    res = refine_corners(tif, boxes, truth)
    assert not res.ok
    assert res.reason == "already-the-best-fit"


# ------------------------------------------------------- the clamp, which is
# the entire safety argument of the module
def test_no_corner_is_ever_moved_further_than_the_clamp(demo):
    """Over a spread of starting placements, in every direction."""
    tif, boxes, truth, pitch = demo
    for dx in (-0.4, -0.2, 0.0, 0.2, 0.4):
        for dy in (-0.4, 0.0, 0.4):
            res = refine_corners(tif, boxes, _shift(truth, dx * pitch, dy * pitch))
            if not res.ok:
                continue
            moved = _worst(res.corners, _shift(truth, dx * pitch, dy * pitch))
            assert moved <= CLAMP_PITCHES * pitch + 1e-6, (
                f"start ({dx}, {dy}) pitch: a corner moved "
                f"{moved / pitch:.3f} pitches, the clamp is {CLAMP_PITCHES}")


def test_the_clamp_cannot_reach_the_neighbouring_patch():
    """THE CONSTANT **IS** THE SAFETY ARGUMENT, so it is pinned as a constant.

    Every other test here asks whether the code honours the bound. This one
    asks whether the bound is worth honouring, and it is the only test that
    can: raising the limit past one patch pitch does not break any behaviour a
    test can observe — a grid slipped a whole patch reads every patch as its
    neighbour and scores identically on every measure taken inside the boxes —
    it simply lets the fit walk onto the wrong patch and call it a fit.
    Measured: with the clamp at 1.6 pitches, `refine_corners` answers a
    one-patch slip with "already-the-best-fit"."""
    assert CLAMP_PITCHES < 1.0, (
        "a corner allowed to travel a whole patch pitch can reach the "
        "neighbouring patch, where every within-box measure says the grid is "
        "perfect and the profile comes out confidently wrong")


def test_a_whole_patch_slip_is_neither_confirmed_NOR_corrected(demo):
    """THE ONE THAT MATTERS, AND THE LIMIT IT DOCUMENTS.

    From a placement a WHOLE patch out — every box squarely on the neighbouring
    patch, every within-box measure saying the grid is perfect — the fit must
    not move the grid at all: the truth is a patch away and a patch is further
    than it may travel. It comes back "already-the-best-fit", which is honest
    about what was searched and is NOT a statement that the placement is right.

    That is exactly why the message for this reason may not claim the grid is
    on the patches, and must name the check that CAN see a whole-patch slip.
    The first draft of it was headed "The grid is already on the patches"; this
    assertion is what stops that coming back."""
    from workflow import measurement_messages as M
    tif, boxes, truth, pitch = demo
    for dx, dy in ((1.0, 0.0), (-1.0, 0.0), (0.0, 1.0), (0.0, -1.0)):
        start = _shift(truth, dx * pitch, dy * pitch)
        res = refine_corners(tif, boxes, start)
        assert not res.ok, (
            f"start ({dx}, {dy}) pitch: the fit MOVED a grid that is a whole "
            f"patch out — it cannot know which way is right")
        if res.corners is not None:                 # belt and braces
            assert _worst(res.corners, start) <= CLAMP_PITCHES * pitch + 1e-6
    # …and the words the user is given for it. From beta 8 the reshaping is the
    # second half of ONE button (B8-42), so this state is told in Auto align's
    # own ending: both halves looked and neither found anything better.
    title, body = M.scan_align_refusal("no-better").render(
        ref_row="Target reference data", chart_row="Target type")
    assert "already on the patches" not in title.lower(), (
        "this message may not claim the placement is correct — nothing in this "
        "operation can tell a one-patch slip from the right answer")
    assert "Check alignment" in body, (
        "the message must name the check that CAN see what it cannot")


def test_a_placement_too_far_out_is_refused_rather_than_guessed(demo):
    tif, boxes, truth, pitch = demo
    res = refine_corners(tif, boxes, _shift(truth, 1.4 * pitch, 0.0))
    assert not res.ok
    assert res.reason in ("too-far-to-fit", "grid-outside-the-image"), res.reason
    assert res.corners is None


# --------------------------------------------- the read path is not involved
def test_the_read_path_never_calls_the_fit():
    """Nothing changes for a scan unless the button is pressed.

    Proved from the source, and there are two links to prove since B8-42 merged
    the reshaping into Auto align: `refine_corners` is called from exactly one
    place in the whole app, `workflow.scan_placement.place_grid`, and
    `place_grid` is reached from exactly one place, the button's own slot.
    Nothing on the read path — `_run_scanin`, the build, the alignment check —
    can reach either.
    """
    import inspect
    import ui.dialogs.scanin_dialog as sd
    import workflow.scan_placement as sp

    app_files = [Path(sd.__file__).parent.parent.parent]
    callers = []
    for root in app_files:
        for py in sorted(root.rglob("*.py")):
            if any(part in {".venv", "tests", "scripts", "build", "dist"}
                   for part in py.parts):
                continue
            for i, ln in enumerate(py.read_text(encoding="utf-8").splitlines(), 1):
                if "refine_corners" in ln and not ln.strip().startswith("#"):
                    callers.append((py.name, i, ln.strip()))
    assert callers, "the fit is not wired up at all"
    outside = [c for c in callers
               if c[0] not in ("scan_placement.py", "photo_fit.py")]
    assert not outside, f"refine_corners is called outside place_grid: {outside}"

    fn = inspect.getsource(sp.place_grid)
    assert "refine_corners(" in fn, "place_grid does not run the fit"
    slot = inspect.getsource(sd.ScannerProfileDialog._on_auto_align)
    assert "place_grid(" in slot, "the button does not run the placement"
    reads = inspect.getsource(sd.ScannerProfileDialog._on_check_alignment)
    assert "place_grid" not in reads and "refine_corners" not in reads


def test_only_a_non_tiff_reaches_the_converter():
    """`as_tiff` is called on every pick, and returns immediately for a TIFF —
    the guard is inside it, tested above, and this pins that the dialog has not
    grown a second path that skips it."""
    import inspect
    import ui.dialogs.scanin_dialog as sd
    src = inspect.getsource(sd.ScannerProfileDialog._pick_scan)
    assert "as_tiff" in src
    assert 'self._cur_shot()["source"] = picked' in src, (
        "the file the user picked must be remembered, or the outputs are "
        "named after a temporary working copy")


def test_the_tooltip_names_what_only_this_button_can_do(qapp, tmp_path):
    """The button's tooltip must say what pressing it will DO and when to
    press it — in the picture, not in the code.

    Basti, 2026-09-04: *"i don't really get what the fit to the patches button
    does differently to the auto align button"*. That was two buttons, and the
    answer was to make it one (B8-42): a search that finds the chart anywhere
    in the frame, and a reshaping that lets the grid lean the way a photograph
    does — a search alone can only ever hand back a RECTANGLE, and a sheet
    photographed off square is not one.

    So the surviving tooltip has to carry both halves plus the prerequisite,
    because the second half is the part nobody would guess is there. This
    checks it says the four things that matter, in whatever wording a later
    edit chooses: that the whole picture is searched, that a photograph is not
    a rectangle, that it falls back to the corners the USER placed, and that a
    refusal changes nothing.
    """
    from core.settings import AppSettings
    from ui.dialogs.scanin_dialog import ScannerProfileDialog

    class _Runner:
        is_running = False

        def run(self, *a, **k):
            raise AssertionError("no Argyll in this test")

    d = ScannerProfileDialog(_Runner(), AppSettings())
    assert not hasattr(d, "_fit_patches_btn"), (
        "the separate 'Fit to the patches' button is back — B8-42 merged it "
        "into Auto align, and two buttons for one job is the thing that was "
        "wrong")
    tip = d._auto_align_btn.toolTip()
    assert tip, "the button has no tooltip at all"
    low = tip.lower()
    assert "whole picture" in low or "searches the whole" in low, (
        "the tooltip does not say the whole picture is searched, which is why "
        "the corners do not have to be right first")
    assert "rectangle" in low, (
        "the tooltip does not say a photographed sheet is no longer a "
        "rectangle — that is the half of this button nobody would guess is "
        "there, and the reason the second button existed at all")
    assert "corners you placed" in low, (
        "the tooltip does not say it falls back to the corners the USER "
        "placed; without that there is no reason to place them first")
    assert "leaves your corners" in low or "leaves them" in low, (
        "the tooltip does not say a refusal changes nothing")
