"""Persistent application settings via QSettings."""
from __future__ import annotations

from typing import Any

from PyQt6.QtCore import QSettings

from core.logger import get_logger
from core.platform_paths import default_argyll_bin_dir, is_macos, is_windows

log = get_logger(__name__)

DEFAULTS: dict[str, Any] = {
    # ArgyllCMS
    "argyll_bin_path":           default_argyll_bin_dir(),
    "custom_output_path":        "",       # "" = ~/ChromIQ/
    # Step 1 — chart creation
    "chart_mode":                "guided",
    "chart_instrument":          "i1",
    "chart_paper":               "A4",
    "chart_pages":               1,
    "chart_double_density":      False,
    "chart_disable_left_border": False,
    # Print info into the i1Pro left clip strip (auto-applies in guided when
    # gating holds: instrument i1/p3, -L off, paper >= A4/Letter).
    "chart_left_clip_info":      False,
    "targen_device_type":        "2",      # Print RGB
    "targen_patches":            0,        # 0 = auto-computed
    # Neutral-patch anchor: the total patch count at which a chart gets the
    # standard 32 grey / 4 white / 4 black. Neutral counts scale relative to
    # this in both Guided and Manual mode (lower = denser, higher = sparser).
    # Default 560 = the i1Pro+A4-landscape reference layout; see
    # workflow.chart_creator.REF_BUDGET. Floors/caps still apply.
    "grey_ramp_reference":       560,
    "targen_good_mode":          True,
    "targen_extra_args":         "",
    "printtarg_dpi":             300,
    "printtarg_extra_args":      "",
    # i1Pro chart layout default: combined -m/-M margin + -a patch scale preset.
    # Applied when instrument == "i1" in both guided and manual modes. Other
    # instruments (p3, CM, SS) are unaffected and keep their existing defaults.
    # See data/patch_db.I1PRO_DEFAULT_PRESETS for the available preset keys.
    "i1pro_default_preset":      "m10_a0.95",
    # Custom ChromIQ chart-layout engine (issue #93). When True, charts are
    # generated by workflow/layout_engine instead of ArgyllCMS printtarg.
    # This toggle governs the MANUAL tab — default ON since 4.0.0 (Knut,
    # 2026-08-13: the engine "is better than printtarg, and deserves to be
    # the default"; schema 18 migrates users pinned to the old False by a
    # Settings→Save). printtarg stays one untick away, incl. the
    # printtarg-based built-in presets, which set their own layout. GUIDED
    # mode always uses the engine: it reproduces printtarg's Guided geometry
    # for every instrument/paper/option (verified 161/161, see the parity
    # matrix) — see _should_use_engine. Affects chart *generation* only,
    # never measurement.
    "use_chromiq_layout_engine": True,
    # Layout-engine presets (issue #93) are stored as user-browsable .json files
    # under presets_dir()/"Chart Layout" via core.preset_store — like the manual
    # tab presets — not in QSettings, so they can be shared/backed up externally.
    # When True, on i1Pro / i1Pro 3+ charts at paper >= A4/Letter:
    #   • Force printtarg -L (no native clip strip).
    #   • Post-process the TIFF to shift patches right by ~28 mm, creating a
    #     fresh white strip on the left.
    #   • Always stamp ChromIQ left-clip content (spectrum bar + 3 text columns)
    #     into that strip.
    #   • Skip the right-margin command/notes stamp (its area is now off-page).
    # Outside those conditions the setting has no effect.
    "i1pro_chromiq_clip_style":  False,
    # Auto-update the Create-Chart preview when a layout setting changes (only
    # once a chart has been generated/loaded). Re-lays-out the existing patch set
    # so it's fast (no targen), and suppresses the "room left on the last page"
    # pop-up while on. Default off (opt-in).
    "auto_update_preview":       False,
    # Step 2 — print
    "last_printer":              "",
    "print_input_slot":          "",
    "print_media":               "",
    "print_media_type":          "",
    "print_quality":             "",
    # Default to the OS print dialog on macOS *and* Windows.  The macOS native
    # path now reliably disables colour management for every driver — including
    # Canon, which previously colour-managed the chart regardless — by
    # replicating ColorByte Print-Tool's recipe: it declares the printer's own
    # device profile as the *application* output intent (identity transform =
    # true passthrough) and sets AP_ApplicationColorMatching on the session, in
    # addition to the driver's own no-colour key (e.g. Canon CNIJIntent2=1001).
    # See workflow/native_print_macos.py.  macOS users can still opt back to
    # ChromIQ's lp path in Settings; Windows has no lp path so it stays
    # force-locked on there (in get()).
    "use_native_print_dialog":   is_windows() or is_macos(),
    "confirm_before_printing":   True,
    # ChromIQ lp pipeline only (macOS): when CUPS rejects PostScript (every
    # non-PostScript printer — Apple's CUPS ships no PS→raster chain), retry
    # with a ChromIQ-generated exact-size PDF instead of the raw TIFF.  The
    # raw-TIFF route hands placement to Apple's cgimagetopdf, which shrinks
    # full-page charts ~3% to fit the imageable area and ignores every
    # ppi/scaling option; the PDF places the chart 1:1 (overhang clips at the
    # hardware margins, like ColorSync Utility) and stays colour-passthrough
    # (untagged device RGB, verified no-ink against Canon + Epson PPDs).
    # Irrelevant while use_native_print_dialog is on (no lp jobs then) —
    # Settings greys it out accordingly.  Off until hardware-verified.
    "pdf_print_fallback":        False,
    # Step 3 — measure
    "measure_disable_bidir":       True,
    # Suppresses the "forcing bidirectional on a non-randomised chart" warning
    # dialog once the user ticks "Don't show this again".
    "measure_hide_nonrandom_bidir_warning": False,
    # How many lines of its own text every log panel shows. Knut asked for 9
    # (beta.120: "only 6 lines of text are visible, but showing 9 is better");
    # it is a setting rather than a constant now because Basti asked for the
    # panels to be draggable, remembered, shared by every tab, and reset by
    # Restore Factory Defaults — all four of which fall out of one shared key.
    "log_visible_lines":           9,
    "measure_suppress_warnings":   True,
    "measure_extra_args":          "",
    # -T IS ON BY DEFAULT, AT 0.7.
    #
    # chartread's -T multiplies the instrument's patch consistency threshold:
    # the driver takes many readings across one patch and rejects the strip when
    # they disagree by more than that (`(maxavg - minavg)/norm > PATCH_CONS_THR`,
    # i1pro_imp.c:6596; the constant is 0.1 on the i1Pro, 0.05 on the ColorMunki).
    # So it measures how EVEN a printed patch is — which is a print-quality
    # signal, not an obstacle: an uneven patch means a clogging nozzle, low ink
    # or a banding toner roller, and catching that while measuring is far
    # cheaper than finding it in a finished profile.
    #
    # beta.140 switched this off after reading a high misread count in Knut's
    # logs as evidence. That reading was wrong: those failures were deliberately
    # provoked for bug-fixing. He asked for the default back, and he is right —
    # 0.7 is a tested value that accepts quite large variation and still catches
    # real problems.
    "measure_tolerance_enabled":           True,
    "measure_tolerance_value":             0.7,
    "manual2_chartread_tolerance_enabled": True,
    # TI2 layout editor — randomised tagging. Well-mixed charts are tagged
    # automatically on save; this remembers whether to FORCE the tag on a
    # layout the safety check considers structured, and whether the user has
    # dismissed the force-risk warning.
    "ti2_editor_force_tag":              False,
    "ti2_editor_force_tag_hide_warning": False,
    # Step 4 — profile
    "colprof_algorithm":         "l",
    "colprof_quality":           "m",
    "colprof_extra_args":        "",
    # Step 5 — check & refine
    "profcheck_de_formula":      "k",       # "" / "-c" / "-k"
    "profcheck_intent":          "a",       # "a" = absolute,  "r" = relative
    "profcheck_sort":            True,
    "profcheck_verbosity":       "2",       # "1" = summary,  "2" = per-patch
    "profcheck_fwa_enabled":     False,
    "profcheck_fwa_illum":       "D50",
    "profcheck_illum":           "D50",
    "profcheck_observer":        "1931_2",
    "profcheck_prune_enabled":      False,
    "profcheck_prune_value":        3.0,
    "profcheck_x3dom":              False,
    "profcheck_refine_threshold":   2.0,
    # Step 5 — gamut viewer (iccgamut)
    "gamut_intent":              "a",     # a=absolute, r=relative, p=perceptual, s=saturation
    "gamut_pcs":                 "l",     # l=Lab, j=CIECAM02 Jab
    "gamut_sres":                20.0,    # surface resolution
    "gamut_axes":                True,    # show axes + white/black point
    "gamut_cusps":               False,   # cusp markers
    "gamut_edges":               False,   # edge plot
    "gamut_function":            "f",     # f=forward, b=backward
    "gamut_themed_colors":       True,   # remap vertex colors to app palette
    # Hide the log panel on every tab (Basti, 2026-08-07). Off by default:
    # the log is where a failure explains itself, so it is opt-out.
    "hide_log_output":           False,
    # Calibration workflow
    "calibration_mode":          False,
    "printcal_smoothing":        1.0,
    "printcal_verbosity":        1,
    "printcal_mode":             "initial",
    "applycal_mode":             "apply",
    "applycal_verbose":          False,
    # ChromIQ-style refinement: merge a pre-conditioning profile's measurement
    # data into the freshly measured chart before building (see workflow/ti3_merge.py)
    "chromiq_refinement":        False,
    # Gamut-mapping engine for the profile engine's perceptual/saturation B2A
    # tables: "fast" = ChromIQ's built-in Python mapper; "argyll" = the bundled
    # chromiq-gammap helper running Argyll's real gamut mapper (bit-exact,
    # slower). Falls back to "fast" when the helper binary isn't present.
    "gammap_mode":               "fast",
    # Chart-reading engine for the Measure tab (#126): "chromiq" = the bundled
    # chromiq-chartread fork (JSON protocol, per-strip autosave, direct strip
    # jumps, live patch feedback) — the default from v3.14.0; "argyll" = stock
    # chartread over a PTY (the classic path). Falls back to "argyll" at runtime
    # when the helper binary isn't present.
    "chartread_engine":          "chromiq",
    # Opt-in (Settings → Beta): let the ChromIQ engine also drive XY tables
    # (GretagMacbeth SpectroScan) and autonomous chart readers (X-Rite i1iSis,
    # DTP70). Off by default → those modes route through stock chartread, which
    # is the proven path for them. Not yet verified on that hardware, so it's
    # opt-in for the adventurous (and for us to test). See --xychart.
    "engine_all_modes":          False,
    #: Let the scanner / camera tools accept a SpectroScan hexagonal chart.
    #: Off = the long-proven behaviour, which refuses them. The chart itself
    #: profiles correctly — measured end to end — but scanin's chart FINDER can
    #: abort the read on a honeycomb even when the four corners are given, and
    #: above a Sample area of ~64 % the sampling box escapes the hexagon and
    #: reads its neighbours. Until both are solved this stays opt-in.
    "scanner_hex_charts":        False,
    # Faster instrument connection: skip Argyll's slow phantom-serial-port probe
    # (macOS Bluetooth/debug ports, Linux rfcomm) so a USB spectro connects
    # nearly instantly. Default on; real USB-serial adapters are never excluded.
    "fast_instrument_connect":   True,
    # Automatic calibration retries (#126, mavtop): how many extra times the
    # chart-reading engine retries a failed instrument calibration before giving
    # up. An ageing i1Pro's lamp can need several strikes to burn in, so a higher
    # value rescues instruments that fail the first attempt. 3 = 4 tries in total.
    "cal_auto_retries":          3,
    # Measurement report (#126, Knut): when True, ChromIQ builds and saves a
    # dated accuracy report (mean/worst ΔE, worst patches, white/black) to the
    # run's reports/ folder after every measurement, so reports of the same
    # chart accrue and can be compared over time (ink/printer/instrument drift).
    "save_measurement_report":   True,
    # Measurement Report Pass thresholds (ΔE00) — the defaults the report opens
    # with; the user can change them here and per-report in the window (Knut).
    "report_pass_threshold_avg": 2.0,
    "report_pass_threshold_max": 3.0,
    # Measurement Report title/filename prefixes (#130, Knut). The report picks
    # the profiling or verification prefix from whether its measurements carry
    # the CHROMIQ_VERIFICATION marker; the full title/filename is
    # "<prefix>[ - <profile name>] - <date_time>". "report_add_profile_name"
    # inserts the profile (chart) name before the date. Editable in Settings →
    # Reports.
    "report_title_profiling":    "Measurement Report - Profiling of Printer",
    "report_title_verification": "Measurement Report - Verification of Profile",
    "report_add_profile_name":   True,
    # Patch-reading error limit (#126, Knut): the ΔE at which a just-measured
    # patch gets the red warning outline in the engine's live split-patch
    # preview. Generous by default so only near-certain misreads are flagged.
    "patch_read_warn_de":        50.0,
    # Whether a patch must ALSO be unusual for its own strip to be flagged
    # (Knut's option (c), #131 2026-07-27). On = today's behaviour.
    "patch_warn_outlier_fence":  True,
    # Measurement sound feedback (#131, Phase 1). Master switch lives on the
    # Measure tab; per-event choices and the optional user sounds folder on the
    # Preferences → Sounds / Paths tabs. Off by default (opt-in comfort feature).
    "sound_enabled":             False,
    # --- measurement pace (#131 Phase 2) ---------------------------------
    # Warn when the instrument is being swiped too fast to gather enough light
    # per patch. The judgement is made in TIME per patch, which is what we can
    # actually measure; when the instrument's sampling rate is known the same
    # threshold is expressed as "minimum samples per patch" (Knut's method:
    # samples ≈ seconds × rate). Rate 0 = not known for this instrument, so no
    # sample count is claimed — ChromIQ never invents that number.
    # Measurement progress bar (#153, Knut): the percentage and coloured fill
    # in the strip above the chart preview while a chart is being measured.
    # Off means neither is shown and no patches are counted.
    "measure_progress_bar":      True,
    "pace_hint_enabled":         True,
    "pace_min_samples":          8,
    "pace_min_patch_ms":         100,
    # How close to the limit a strip has to be before it is called "close to
    # the limit", as a percentage of the instrument's own limit (#149, Knut
    # 2026-08-14). It was a fixed 35%, wide enough to call a 521 ms strip
    # "close" to a 400 ms limit. 0 = only ever warn about a strip that is
    # genuinely too fast.
    "pace_marginal_percent":     10,
    # Strip length used for the live "fastest a strip may be read" figures in
    # Preferences → Measurement. Per instrument since #130 (Knut, 2026-07-29):
    # pace_estimate_patches_<model>, seeded from measure_pace.ESTIMATE_PATCHES.
    "pace_sample_hz_i1pro":      0.0,
    "pace_sample_hz_colormunki": 0.0,
    "sound_folder":              "",     # blank = the bundled default pack
    # Wake the audio device with an inaudible clip before playing a real sound
    # (#148). OFF, and staying off unless a user asks for it: on the machine
    # this was written for it silenced every sound in the app instead of making
    # the first one louder. See core.sound.warm_up_enabled for the full story.
    "sound_warm_up_device":      False,
    # ONE source of truth, spliced in below from core.sound.DEFAULT_CHOICE.
    # These used to be written out again here, and the second copy quietly won:
    # changing a default in core.sound had no effect at all, because AppSettings
    # answered from its own stale copy first (found while giving Knut the
    # defaults he asked for in #148).
    # "Read again & average" — master switch. OFF (default) restores the classic
    # behaviour: a finished full read proceeds straight to Build Profile. ON adds
    # the post-read completion dialog offering measure-again / average.
    "averaging_enabled":         False,
    # When averaging is enabled, how repeated reads are combined: "mean" | "median"
    # (median == argyll `average -e`; only differs from mean at 3+ reads)
    "average_method":            "mean",
    # UI state
    "window_geometry":           None,
    "active_tab":                0,
    # False since #130 (Knut, 2026-07-29): "When starting fresh, it should
    # always start in first tab." Switch it on in Preferences → General to have
    # ChromIQ reopen wherever you left off.
    "restore_last_tab":          False,
    "restore_last_session":      False,
    # The "Location being edited" line under the Profile-run bar. Sebastian
    # asked (#130, 2026-07-31) whether it could be hidden to simplify the
    # interface for people who never run verifications; Knut agreed, and settled
    # the wording and the polarity: *"I prefer 'Show the location being edited',
    # enabled shows."* Default ON — when file handling goes wrong that line is
    # the first thing anyone looks at, so hiding it by default would cost the
    # one detail that usually explains the problem.
    "show_location_being_edited": True,
    "appearance":                "auto",   # "light" | "dark" | "auto"
    "language":                  "en",     # ISO code; applied on restart (core/i18n.py)
    # When True, file open/save/folder pickers use the OS-native dialog instead
    # of ChromIQ's themed one. Native is much faster to populate on Windows, but
    # it's the OS's own dialog: it can't carry ChromIQ's custom sidebar shortcuts
    # or the built-in image-preview pane (Qt/OS limitation — see ui/widgets.py).
    "use_native_file_dialogs":   False,
    "show_welcome_dialog":       True,
    "show_splash":               True,     # startup branding splash (main.py)
    "window_maximized":          False,
    "window_fullscreen":         False,
    # Session restore — only the target name is stored; every artefact path is
    # derived from the project's current run on restore (see main_window).
    "session_target_name":       "",
    # #134: remembered choices in the "chart already has a measurement" prompt.
    "overlay_prompt_show_overlay": True,
    "overlay_prompt_resume":       False,
    # #130: the open project's actual folder when it's nested in a sub-folder of
    # the ChromIQ folder (blank for a direct child). Restores nested projects.
    "session_project_root":      "",
    # Diagnostics — off by default; flip to True to log per-strip highlighter
    # math (id, global_idx, page, local_idx) to chromiq.log for investigating
    # detection drift.
    "debug_highlighter":         False,
    # Margin inspector (Create Chart) — measure the realised page margins of the
    # generated preview, compare to per-(instrument, paper+orientation) minimum
    # thresholds, and flag violations for jig/rig users.
    "margin_inspector_show":     True,    # show the "Measured from Preview" frame
    "layout_info_show":          True,    # show the "Chart layout information" panel
    "margin_violation_notify":   True,    # warn when a measured margin < threshold
    "margin_guides_show":        False,   # dotted threshold guide lines on preview
    "margin_measured_guides_show": False,  # long dotted lines at the measured margins
    "margin_coords_show":         False,   # cross-hair + paper-mm/inch readout on pointer (#29)
    # Ruler helper markers (#152, Knut): short dashes printed along all four
    # page edges so a ruler can be laid on the sheet while measuring. These are
    # printed into the chart, not a preview overlay.
    "helper_markers_show":        False,
    "helper_marker_edge_mm":      2.0,
    "helper_marker_len_mm":       2.0,
    "declutter_on_load":          True,    # tidy legacy flat folders into v2 subfolders on file load (#36)
    "export_shuffled_pxf":        False,   # also write a patch-order-shuffled i1Profiler .pxf copy (Nelson)
    "margin_thresholds":         "",      # JSON blob; "" → default_margin_thresholds()
    # Scanner/camera profiling: misalignment-check thresholds (Knut #108).
    # Editable in Settings → Scanner; the defaults carry a buffer for real
    # scans (noisier than the built-in demo images).
    #   (the ΔE-vs-aims share check was retired in beta.130 — real prints
    #   can't reach the chart's ideal aims, so it flagged aligned scans)
    "scanner_selfcheck_peak":    30.0,    # colprof self-check peak err → warning
    "scanner_selfcheck_avg":     12.0,    # …AND avg err must exceed this too
    # Check-alignment probe verdict: the user's position competes with the
    # 8-direction probe star on Knut's normalised scale (best probe = 1,
    # worst = 0). Calibrated on his real Wolf Faust scan so a 25 % grid
    # offset flags and ≤15 % passes at 50 % sample area (#108).
    "scanner_check_agreement":   0.85,
    # Flank override (Knut's derivative design): patch borders are LINES of
    # high spatial gradient (centred, two scales — symmetric in all 8
    # directions); a box is ON an edge when 3+ CONNECTED sub-cells of its
    # 11x11 grid carry a peak above the grain floor (a line crosses adjacent
    # cells, dust scatters) AND the box is clean at some nearby position.
    # The box's value is its 3rd-hottest cell, minus the page's grain floor,
    # over the page's luminance range — a normalised gradient PEAK, not a
    # step height between neighbouring cells.
    #
    # Both numbers come from scripts/scanner_edge_study.py run on Knut's two
    # real 600 dpi IT8 scans, against scanin's own placement (#119). Boxes
    # over the limit, per case:
    #                          aligned  +5%  +10%  |  +20%  corner-pull
    #   Wolf Faust  @0.20            1    1     2  |   131        4
    #   LaserSoft   @0.20            2    2     1  |   258      160
    # so min_boxes must exceed 2 and not exceed 4 → 3, which is exactly the
    # number Knut specified in the #108 design. 2 raises a false alarm on his
    # own aligned LaserSoft (its printed bars are real edges near box rims);
    # the 7 previously shipped misses the pulled-corner case entirely, since
    # only a handful of patches near that corner ever straddle a border.
    "scanner_flank_limit":       0.20,
    # 0 = edge detection off (the other misalignment checks stay active).
    "scanner_flank_min_boxes":   2,
    # How many interconnected sensing sub-cells inside ONE reading box must
    # carry an edge — in a straight run, since a border is a line — before
    # that box counts as sitting on an edge (Knut, #119). Guards against
    # grain and specs, which light scattered or compact cells. The count is
    # LITERAL cells of the actual sensing grid (6 means 6 — Knut rejected a
    # round that converted it to a reference scale); max 20 = 20 of the 30
    # cells on a side of the 30×30 grid. 8 is Knut's pick: 6 was already
    # clean on his scans, 8 adds buffer.
    "scanner_flank_min_cells":   8,
    # Bumped by AppSettings.migrate() — see SETTINGS_SCHEMA.
    "settings_schema":           0,
    # Settings → Paths (Knut #108): where "Install profile" copies the .icc.
    # Empty = the platform's per-user colour-profile folder.
    "profile_install_dir":       "",
    # Strip-indicator styling (Knut #93): the per-chart detail controls moved to
    # Settings → Chart Layout. These are the app-wide styling for EVERY engine
    # chart — overlaid at read time in TabChart._current_layout_recipe, so the
    # styling fields a preset/saved-defaults recipe carries are inert history.
    # Keys mirror the LayoutRecipe.indicator_*/underline_*/strip_label_offset
    # fields.
    "strip_indicator_font":          "JetBrains Mono",
    "strip_indicator_size_mm":       0.0,   # 0 = auto (instrument text height)
    "strip_indicator_bold":          False,
    "strip_indicator_italic":        False,
    "strip_indicator_rotation":      0,     # 0 | 90 | 180 | 270
    "strip_indicator_align":         "left",
    "strip_label_offset_mm":         0.0,
    "strip_underline_mode":          "off",  # "off" | "colored" | "black"
    "strip_underline_thickness_mm":  0.5,
    "strip_underline_gap_mm":        0.5,
}

# Map LayoutRecipe styling field → its settings key, so the panel and the
# recipe-overlay helper agree (Knut #93). show_strip_indicators stays per-chart
# (it's a layout decision, not styling — presets keep it).
INDICATOR_STYLE_KEYS = {
    "indicator_font":          "strip_indicator_font",
    "indicator_size_mm":       "strip_indicator_size_mm",
    "indicator_bold":          "strip_indicator_bold",
    "indicator_italic":        "strip_indicator_italic",
    "indicator_rotation":      "strip_indicator_rotation",
    "indicator_align":         "strip_indicator_align",
    "strip_label_offset_mm":   "strip_label_offset_mm",
    "underline_mode":          "strip_underline_mode",
    "underline_thickness_mm":  "strip_underline_thickness_mm",
    "underline_gap_mm":        "strip_underline_gap_mm",
}


# ---------------------------------------------------------------------------
# Margin-threshold seed defaults
# ---------------------------------------------------------------------------
# Per-(instrument, paper+orientation) minimum margins (mm) the inspector warns
# below. Keyed "<instrument>|<paper> <Orientation>". These are *editable seed
# values* (a starting point users adjust to their own rig), NOT physical minima.
# The i1Pro values come from the X-Rite/enlarged-ruler analysis (≈11 mm white
# run-up on the narrow side, the label side ending up larger). ColorMunki seeds
# are derived empirically from the shipped, practically-tested presets
# (scripts/derive_margin_seeds.py).
#
# The white run-up the i1Pro/ColorMunki needs is along the **scan direction**
# (the strip length). printtarg lays strips down the page, so for a *portrait*
# sheet the scan-direction edges are Top and Bottom; for *landscape*, Left and
# Right. Cross-scan side margins (the other pair) aren't the binding constraint,
# so they're left at 0 (unchecked) — which also stops shipped presets (e.g. the
# i1Pro A4 chart's 8 mm cross-scan margin) from false-alarming. ColorMunki values
# are derived empirically from the shipped, practically-tested presets
# (scripts/derive_margin_seeds.py: Top ≈ 24 mm, Bottom ≈ 11 mm) and rounded just
# below the smallest known-good margin so those presets read OK out of the box.
_I1_DESC = "i1Pro ruler / jig"
_CM_DESC = "ColorMunki ruler / jig"
# Knut #82: thresholds are 10 mm sides/bottom + 24 mm Top (label edge) for the
# i1Pro, and 6 mm sides/bottom + 24 mm Top for the ColorMunki. ColorMunki uses
# the same values for *every* paper size, so its seeds cover all papers × both
# orientations; the i1Pro table lists the orientations its presets actually use.
# (Top is still tentative — editable per combo.)
_MARGIN_PAPERS_ALL = ("A4", "Letter", "A3", "A3+", "A2", "Tabloid", "Legal")


def _seed_rows(instr, desc, side, top, combos, bottom=None):
    """*bottom* defaults to *side*, which is what every instrument used before
    the ColorMunki gained its own bottom margin (Knut, #131 2026-07-27)."""
    b = side if bottom is None else bottom
    return {
        f"{instr}|{paper} {orient}":
            {"L": side, "R": side, "T": top, "B": b, "desc": desc}
        for paper, orient in combos
    }


# i1Pro confirmed values (#82): the primary reading orientation of each common
# paper needs the 26 mm left clip border, 38 mm label-edge top, 9 mm elsewhere;
# every other i1Pro paper/orientation gets a plain 9 mm all round.
_I1_PRIMARY = {"L": 26, "R": 9, "T": 38, "B": 9, "desc": _I1_DESC}
# i1Pro 3+ (#82): the larger body needs a touch more on the clip + label edges
# (28 / 40 instead of 26 / 38); provisional until confirmed.
_I1P3_DESC = "i1Pro 3+ ruler / jig"
_I1P3_PRIMARY = {"L": 28, "R": 9, "T": 40, "B": 9, "desc": _I1P3_DESC}
# A4 / Letter are also on the primary (jig) list in LANDSCAPE: the i1Pro jig
# can read those sheets landscape too, and Knut wants the same clip/label
# margins there as portrait (#125). schema 7 upgrades a stored blob's plain-9
# entries for these two combos in place.
_PRIMARY_COMBOS = (
    "A4 Portrait", "Letter Portrait", "A3 Landscape", "Tabloid Landscape",
    "A4 Landscape", "Letter Landscape")
# The combos that gained the jig margins in schema 7 (used by the migration).
_SCHEMA7_LANDSCAPE_COMBOS = ("A4 Landscape", "Letter Landscape")
_ALL_COMBOS = [(p, o) for p in _MARGIN_PAPERS_ALL
               for o in ("Portrait", "Landscape")]

# i1Pro A4 Portrait and A3 Landscape read a full-height (297 mm) strip; with the
# 38 mm label-edge top a 9 mm bottom leaves a 250 mm strip — over the i1Pro's
# 240 mm strip-length limit, so the default chart never fit. These two combos get
# a 19 mm bottom (297 − 38 − 19 = 240) so the seeded chart is legal (Knut,
# #130 beta-2 test). Letter Portrait (279 mm) already fits and stays at 9 mm.
_I1_TALLBOTTOM_COMBOS = ("A4 Portrait", "A3 Landscape")
_I1_TALLBOTTOM_B = 19


def _i1_primary(combo: str) -> dict[str, Any]:
    """The i1Pro jig margins for *combo*, with the taller bottom on the two
    full-height-strip combos (see :data:`_I1_TALLBOTTOM_COMBOS`)."""
    d = dict(_I1_PRIMARY)
    if combo in _I1_TALLBOTTOM_COMBOS:
        d["B"] = _I1_TALLBOTTOM_B
    return d


_MARGIN_SEED: dict[str, dict[str, Any]] = {
    **_seed_rows("i1Pro", _I1_DESC, 9, 9, _ALL_COMBOS),
    **{f"i1Pro|{c}": _i1_primary(c) for c in _PRIMARY_COMBOS},
    **_seed_rows("i1Pro 3+", _I1P3_DESC, 9, 9, _ALL_COMBOS),
    **{f"i1Pro 3+|{c}": dict(_I1P3_PRIMARY) for c in _PRIMARY_COMBOS},
    # Knut, #151 2026-08-14: 33 mm at the top on every page size, not 30. The
    # ColorMunki has two knobs on its underside that catch on the edge of the
    # sheet as a strip is started, so the head needs a little more paper in
    # front of the first patch than the optics alone would suggest. The bottom
    # stays at 10 mm and the sides at 6 mm (#131).
    **_seed_rows("ColorMunki", _CM_DESC, 6, 33, _ALL_COMBOS, bottom=10),
}


def _same_margin(a: dict[str, Any], b: dict[str, Any]) -> bool:
    """True when two margin entries carry the same L/R/T/B values (the ``desc``
    label is ignored — only the numeric thresholds decide equality)."""
    try:
        return all(abs(float(a.get(k, 0)) - float(b.get(k, 0))) < 1e-9
                   for k in ("L", "R", "T", "B"))
    except (TypeError, ValueError):
        return False


#: What the ColorMunki rows held before schema 13, so a stored blob can be
#: upgraded without touching a value the user set themselves.
_CM_OLD_MARGINS = {"L": 6, "R": 6, "T": 24, "B": 6}
_CM_NEW_MARGINS = {"L": 6, "R": 6, "T": 30, "B": 10}

#: Schema 19 (#151): the top goes 30 → 33 mm. Both earlier defaults are listed
#: because a blob may hold either — 6/6/24/6 from before schema 13 if the user
#: has never opened Preferences since, or 6/6/30/10 from schema 13 onwards.
_CM_TOP33_OLD = (_CM_OLD_MARGINS, _CM_NEW_MARGINS)
_CM_TOP33_MARGINS = {"L": 6, "R": 6, "T": 33, "B": 10}


def upgrade_colormunki_margins(
    table: dict[str, dict[str, Any]]
) -> tuple[dict[str, dict[str, Any]], bool]:
    """Give every ColorMunki page combination 30 mm top and 10 mm bottom
    (schema 13, Knut #131), returning ``(table, changed)``.

    Only rows still holding the old 6/6/24/6 default are changed — anything the
    user adjusted in Settings is left exactly as it is. Pure, so the rule is
    unit-tested directly.
    """
    changed = False
    for key, row in list(table.items()):
        if not key.startswith("ColorMunki|"):
            continue
        if _same_margin(row, _CM_OLD_MARGINS):
            row.update(_CM_NEW_MARGINS)
            changed = True
    return table, changed


def upgrade_colormunki_top_margin_33(
    table: dict[str, dict[str, Any]]
) -> tuple[dict[str, dict[str, Any]], bool]:
    """Give every ColorMunki page combination a 33 mm top margin (schema 19,
    Knut #151), returning ``(table, changed)``.

    *"Due to two knobs underneath the colormunki, which keeps getting caught in
    the paper edge when starting a strip, the top margin instrument limit should
    be set to 33.0 mm."*

    Only rows still holding a shipped default are raised — either the pre-schema-13
    6/6/24/6 or the schema-13 6/6/30/10. A threshold the user tuned for their own
    rig is left exactly as it is, because these values are seeds to adjust, not
    physical minima.
    """
    changed = False
    for key, row in list(table.items()):
        if not key.startswith("ColorMunki|"):
            continue
        if any(_same_margin(row, old) for old in _CM_TOP33_OLD):
            row.update(_CM_TOP33_MARGINS)
            changed = True
    return table, changed


def upgrade_margin_landscape_jig(
    table: dict[str, dict[str, Any]]
) -> tuple[dict[str, dict[str, Any]], bool]:
    """Give i1Pro / i1Pro 3+ A4 & Letter *Landscape* the jig margins (schema 7,
    #125), returning ``(table, changed)``. A combo is upgraded only when it is
    absent or still equals the old plain-9 default — a customised value is kept.
    Pure (no I/O) so the rule is unit-tested directly."""
    changed = False
    for instr, primary in {"i1Pro": _I1_PRIMARY, "i1Pro 3+": _I1P3_PRIMARY}.items():
        old_plain = {"L": 9, "R": 9, "T": 9, "B": 9}
        for combo in _SCHEMA7_LANDSCAPE_COMBOS:
            key = f"{instr}|{combo}"
            cur = table.get(key)
            if cur is None or _same_margin(cur, old_plain):
                table[key] = dict(primary)
                changed = True
    return table, changed


def upgrade_margin_i1pro_tall_bottom(
    table: dict[str, dict[str, Any]]
) -> tuple[dict[str, dict[str, Any]], bool]:
    """Give i1Pro A4 Portrait / A3 Landscape the 19 mm bottom margin (schema 12,
    #130), returning ``(table, changed)``. A combo is upgraded only when it is
    absent or still equals the old jig default (:data:`_I1_PRIMARY`, bottom 9) —
    a value the user customised is kept. Pure (no I/O) so it is unit-tested
    directly."""
    changed = False
    for combo in _I1_TALLBOTTOM_COMBOS:
        key = f"i1Pro|{combo}"
        cur = table.get(key)
        if cur is None or _same_margin(cur, _I1_PRIMARY):   # _I1_PRIMARY has B=9
            table[key] = _i1_primary(combo)
            changed = True
    return table, changed


def default_margin_thresholds() -> dict[str, dict[str, Any]]:
    """A fresh copy of the seed threshold table (see :data:`_MARGIN_SEED`)."""
    import copy

    return copy.deepcopy(_MARGIN_SEED)


def parse_margin_thresholds(raw: str) -> dict[str, dict[str, Any]]:
    """Decode the stored margin-threshold JSON blob (``""`` → seed defaults)."""
    import json

    if not raw:
        return default_margin_thresholds()
    try:
        doc = json.loads(raw)
        if isinstance(doc, dict):
            return doc
    except (ValueError, TypeError):
        log.warning("Corrupt margin_thresholds blob — using seed defaults")
    return default_margin_thresholds()


def serialize_margin_thresholds(table: dict[str, dict[str, Any]]) -> str:
    import json

    return json.dumps(table, ensure_ascii=False)


def margin_combo_key(instrument: str, paper: str, orientation: str) -> str:
    """Canonical "<instrument>|<paper> <Orientation>" threshold key."""
    paper = (paper or "").strip()
    orientation = (orientation or "").strip().capitalize()
    suffix = f" {orientation}" if orientation else ""
    return f"{instrument}|{paper}{suffix}"


# Engine instrument flag → margin-threshold instrument label (matches the seed
# keys + settings_dialog._MARGIN_INSTRUMENTS).
THRESHOLD_INSTR_LABEL = {
    "i1": "i1Pro", "p3": "i1Pro 3+", "CM": "ColorMunki",
    "SS": "SpectroScan", "isis": "i1iSis",
}

# Canonical sheet name keyed by sorted (short, long) mm — so any paper code
# (named, "WxH", rotated) maps to one threshold-combo paper name; orientation is
# carried separately. Mirrors ui.tabs.tab_chart._CANON_PAPER_BY_DIMS.
_CANON_PAPER_BY_DIMS = {
    (210.0, 297.0): "A4",
    (215.9, 279.4): "Letter",
    (215.9, 355.6): "Legal",
    (297.0, 420.0): "A3",
    (329.0, 483.0): "A3+",
    (420.0, 594.0): "A2",
    (279.4, 431.8): "Tabloid",
}


def canonical_paper_name(w_mm: float, h_mm: float) -> "str | None":
    """Best-effort canonical sheet name from page dimensions (mm), or None.

    Tolerant to ~2.5 mm so a measured page still matches a named size."""
    lo, hi = sorted((w_mm, h_mm))
    for (clo, chi), name in _CANON_PAPER_BY_DIMS.items():
        if abs(lo - clo) <= 2.5 and abs(hi - chi) <= 2.5:
            return name
    return None


def thresholds_for_combo(
    table: "dict[str, dict[str, Any]]", instrument_flag: str,
    w_mm: float, h_mm: float,
) -> "dict[str, Any] | None":
    """The margin-threshold entry for an engine instrument flag + page size, or
    None when the combo has no thresholds. Used to enforce the user's minimums
    in the layout engine (#93)."""
    label = THRESHOLD_INSTR_LABEL.get(instrument_flag)
    name = canonical_paper_name(w_mm, h_mm)
    if not label or not name:
        return None
    orientation = "Landscape" if w_mm > h_mm else "Portrait"
    return (table or {}).get(margin_combo_key(label, name, orientation))


# Bump when a shipped default changes in a way that must reach users who have
# the OLD default persisted. Settings → Save writes every key, so a stored
# value otherwise pins a user to the old behaviour for good.
SETTINGS_SCHEMA = 21

# key → the old default(s) it must no longer be stuck on. Only a stored value
# EQUAL to one of the old defaults is dropped (so it falls through to the new
# one); a value the user deliberately chose is never touched.
# The measurement-sound choices come from the sound layer itself, so a default
# can only ever be changed in one place (#148).
def _seed_sound_defaults() -> None:
    from core.sound import ALL_EVENTS, DEFAULT_CHOICE, OFF
    for _event in ALL_EVENTS:
        DEFAULTS[f"sound_choice_{_event}"] = DEFAULT_CHOICE.get(_event, OFF)


_seed_sound_defaults()


_SUPERSEDED_DEFAULTS: dict[str, tuple[float, ...]] = {
    # #119: the old pair (0.30 + a hard-coded 7 boxes) could not detect a grid
    # with one corner pulled in — at 0.30 a pulled corner leaves 0 flagged
    # boxes on a Wolf Faust. Anyone who had ever pressed Save in Settings had
    # 0.30 persisted and would never have received the fix.
    "scanner_flank_limit": (0.30,),
    # schema 2 (#119, Knut's beta.3 test): 3 sensing cells in a row still let
    # a long narrow grey speck (his D20) flag an aligned grid; 5 was his
    # measured clean value, 6 the default with buffer. schema 4: Knut moved
    # the default to 8 for extra buffer alongside the 85 % sensing grid.
    "scanner_flank_min_cells": (3, 6),
    # schema 2 raised the floor to 0.87; schema 5 settles it at 0.85 (Knut's
    # final number for GA) — stored echoes of either shipped default fall
    # through, a deliberately chosen value survives.
    "scanner_check_agreement": (0.85, 0.87),
    # schema 3 (#119, Knut's beta.4 test): with the straight-run cell rule an
    # aligned scan leaves at most 1 edge-flagged patch, so 2 warns earlier
    # without false alarms (his preference after testing).
    "scanner_flank_min_boxes": (3,),
    # schema 9: the patch-read warning floor default moved 20 → 50 ΔE (Nelson's
    # value — with the adaptive per-strip outlier test, 20 still lit up too many
    # legitimately-vivid patches on a scanner/print workflow). A stored echo of
    # the old 20 default falls through to 50; a value the user chose is kept.
    "patch_read_warn_de": (20.0,),
    # schema 15 (#130, Knut 2026-07-29): the minimum readings per patch were
    # re-derived alongside the new per-instrument strip lengths. A stored echo
    # of a shipped default falls through to the new one; a number the user
    # chose themselves survives untouched. (The ColorMunki's earlier 30 → 23
    # step is handled by _migrate_colormunki_min_samples, which names it in the
    # log; 23 → 20 is just another superseded default.)
    "pace_min_samples_i1pro3":     (30,),
    "pace_min_samples_i1pro3plus": (60,),
    "pace_min_samples_colormunki": (23,),
}

# Keys removed outright — replaced by a new setting, so any stored value is
# obsolete regardless of what it was.
_OBSOLETE_KEYS: tuple[str, ...] = (
    # schema 6: the boolean "most accurate gamut mapping" toggle became the
    # gammap_mode picker ("fast" / "argyll"); everyone defaults to "fast".
    "gammap_exact_geometry",
    # schema 15 (#130, Knut 2026-07-29): the one strip length shared by every
    # instrument became a per-instrument "Patches per strip" box
    # (pace_estimate_patches_<model>), so whatever was stored for the common
    # box is obsolete regardless of its value.
    "pace_estimate_patches",
)


class AppSettings:
    def __init__(self) -> None:
        self._qs = QSettings("ChromIQ", "ChromIQ")
        log.debug("Settings loaded from %s", self._qs.fileName())

    def migrate(self) -> list[str]:
        """One-time cleanup of persisted values that merely echo a superseded
        default. Returns the keys dropped. Call once at startup."""
        if int(self._qs.value("settings_schema", 0) or 0) >= SETTINGS_SCHEMA:
            return []
        dropped = []
        for key, olds in _SUPERSEDED_DEFAULTS.items():
            raw = self._qs.value(key, None)
            if raw is None:
                continue
            try:
                if any(abs(float(raw) - old) < 1e-9 for old in olds):
                    self._qs.remove(key)
                    dropped.append(key)
            except (TypeError, ValueError):
                continue
        for key in _OBSOLETE_KEYS:
            if self._qs.value(key, None) is not None:
                self._qs.remove(key)
                dropped.append(key)
        if self._migrate_margin_landscape_jig():
            dropped.append("margin_thresholds[A4/Letter Landscape jig]")
        if self._migrate_margin_i1pro_tall_bottom():
            dropped.append("margin_thresholds[i1Pro A4 Portrait/A3 Landscape bottom→19mm]")
        if self._migrate_colormunki_margins():
            dropped.append("margin_thresholds[ColorMunki top→30mm, bottom→10mm]")
        if self._migrate_colormunki_top_margin_33():
            dropped.append("margin_thresholds[ColorMunki top→33mm]")
        for _k in self._migrate_sound_defaults():
            dropped.append(_k)
        for _k in self._migrate_helper_marker_sizes():
            dropped.append(_k)
        if self._migrate_colormunki_min_samples():
            dropped.append("pace_min_samples_colormunki (30 → 23)")
        if self._migrate_patch_warn_floor():
            dropped.append("patch_read_warn_de (raised value now too high)")
        if self._migrate_save_report_default():
            dropped.append("save_measurement_report (now on by default)")
        if self._migrate_chartread_engine_default():
            dropped.append("chartread_engine (ChromIQ engine now the default)")
        if self._migrate_layout_engine_default():
            dropped.append("use_chromiq_layout_engine (ChromIQ layout engine "
                           "now the Manual default)")
        if self._migrate_restore_last_tab_default():
            dropped.append("restore_last_tab (now off by default)")
        self._qs.setValue("settings_schema", SETTINGS_SCHEMA)
        if dropped:
            log.info("Settings migrated to schema %d; dropped stale defaults: %s",
                     SETTINGS_SCHEMA, ", ".join(dropped))
        return dropped

    def _migrate_save_report_default(self) -> bool:
        """schema 10: saving a measurement report after each measurement is now on
        by default. A stored echo of the old ``False`` default is dropped so it
        resolves to the new ``True``; an explicit ``True`` is already correct.
        (Booleans persist as the string "false", which the float-based
        _SUPERSEDED_DEFAULTS can't match, so this handles it directly.)"""
        raw = self._qs.value("save_measurement_report", None)
        if raw is None:
            return False
        is_true = raw is True or (isinstance(raw, str)
                                  and raw.strip().lower() in ("true", "1", "yes"))
        if not is_true:
            self._qs.remove("save_measurement_report")
            return True
        return False

    def _migrate_restore_last_tab_default(self) -> bool:
        """schema 16 (#130, Knut 2026-07-29): reopening on the last-used tab is
        now OFF by default — *"When starting fresh, it should always start in
        first tab."*

        Preferences → Save writes every key, so anyone who has opened that
        dialog carries a stored ``True`` that is only an echo of the old
        default; that echo is dropped so it resolves to the new value. The
        limitation is the same as every other default change here: a ``True``
        the user chose deliberately is indistinguishable from the echo and is
        dropped too, so anyone who wants the old behaviour ticks the box again —
        which is why the box is still there.
        """
        raw = self._qs.value("restore_last_tab", None)
        if raw is None:
            return False
        is_true = raw is True or (isinstance(raw, str)
                                  and raw.strip().lower() in ("true", "1", "yes"))
        if is_true:
            self._qs.remove("restore_last_tab")
            return True
        return False

    def _migrate_chartread_engine_default(self) -> bool:
        """schema 11 (v3.14.0): the ChromIQ chart-reading engine (#126) is now the
        default. A stored echo of the old ``"argyll"`` default is dropped so it
        resolves to the new ``"chromiq"``; any other stored value (an explicit
        choice) is left untouched. Runtime still falls back to argyll when the
        helper binary is missing."""
        raw = self._qs.value("chartread_engine", None)
        if isinstance(raw, str) and raw.strip().lower() == "argyll":
            self._qs.remove("chartread_engine")
            return True
        return False

    def _migrate_layout_engine_default(self) -> bool:
        """schema 18 (4.0.0, Knut): the ChromIQ layout engine is now the
        Manual default too (Guided has used it all along). A stored echo of
        the old ``False`` default is dropped so it resolves to the new
        ``True``; anything else stays. Charts that exist keep the layout
        recipe recorded in their own file, so nothing already built changes.
        QSettings stores booleans differently per backend — native bool on
        the macOS plist, the strings "false"/"true" in INI — so both spellings
        of the old default are recognised."""
        raw = self._qs.value("use_chromiq_layout_engine", None)
        if raw is None:
            return False
        if raw is False or (isinstance(raw, str)
                            and raw.strip().lower() == "false"):
            self._qs.remove("use_chromiq_layout_engine")
            return True
        return False

    def _migrate_patch_warn_floor(self) -> bool:
        """schema 8 (#49): the patch-read warning outline is now adaptive — a
        patch is flagged only if it is BOTH past this limit AND an outlier within
        its own strip. The false alarms that led people to RAISE the old absolute
        limit (vivid patches sit far from sRGB on a good print) are now handled
        automatically, so a raised value merely hides genuine misreads. Reset any
        value ABOVE the default back to it (drop it → falls back to the default).
        A value the user LOWERED, wanting more sensitivity, is left untouched.
        schema 9: the default floor moved to 50 ΔE, so the reset threshold tracks
        it (a stored echo of the old 20 default is dropped separately via
        _SUPERSEDED_DEFAULTS)."""
        raw = self._qs.value("patch_read_warn_de", None)
        if raw is None:
            return False
        try:
            val = float(raw)
        except (TypeError, ValueError):
            return False
        if val > 50.0 + 1e-9:              # 50.0 is the default floor
            self._qs.remove("patch_read_warn_de")
            return True
        return False

    def _migrate_margin_landscape_jig(self) -> bool:
        """schema 7 (#125): give i1Pro / i1Pro 3+ A4 & Letter *Landscape* the jig
        margins, matching portrait. Upgrades a stored ``margin_thresholds`` blob
        in place, but only for combos that still hold the old plain-9 default —
        a value the user customised in Settings is left untouched. Returns True
        when the blob was changed. Fresh installs need nothing (the seed already
        carries the new values)."""
        raw = self._qs.value("margin_thresholds", None)
        if not raw:
            return False
        try:
            table = parse_margin_thresholds(str(raw))
        except Exception:  # noqa: BLE001
            return False
        table, changed = upgrade_margin_landscape_jig(table)
        if changed:
            self._qs.setValue("margin_thresholds",
                              serialize_margin_thresholds(table))
        return changed

    def _migrate_colormunki_margins(self) -> bool:
        """schema 13 (#131, Knut): the ColorMunki needs 30 mm at the top and
        10 mm at the bottom on every page size. Upgrades a stored
        ``margin_thresholds`` blob in place, but only for rows still holding the
        old 6/6/24/6 default — a value the user set is left untouched. Fresh
        installs need nothing (the seed already carries the new values)."""
        raw = self._qs.value("margin_thresholds", None)
        if not raw:
            return False
        try:
            table = parse_margin_thresholds(str(raw))
        except Exception:  # noqa: BLE001
            return False
        table, changed = upgrade_colormunki_margins(table)
        if changed:
            self._qs.setValue("margin_thresholds",
                              serialize_margin_thresholds(table))
        return changed

    def _migrate_colormunki_top_margin_33(self) -> bool:
        """schema 19 (#151, Knut 2026-08-14): the ColorMunki's top margin goes
        from 30 mm to 33 mm on every page size — the two knobs on its underside
        catch on the edge of the sheet when a strip is started.

        Upgrades a stored ``margin_thresholds`` blob in place, but only rows
        still holding a shipped default. A threshold the user tuned is left
        untouched. Fresh installs need nothing — the seed carries 33 already.
        """
        raw = self._qs.value("margin_thresholds", None)
        if not raw:
            return False
        try:
            table = parse_margin_thresholds(str(raw))
        except Exception:  # noqa: BLE001
            return False
        table, changed = upgrade_colormunki_top_margin_33(table)
        if changed:
            self._qs.setValue("margin_thresholds",
                              serialize_margin_thresholds(table))
        return changed

    def _migrate_sound_defaults(self) -> list:
        """schema 20 (#148, Knut 2026-08-14): three sounds get better defaults.

        After living with the pack through a real measurement he asked for
        *"Patch reading looks off"* to be **bump**, *"Measurement finished"* to
        be **chime-long** and *"Profile build finished"* to be **applause**.

        Preferences → Save writes every key, so anyone who has ever opened that
        dialog carries a stored copy of the old choice that is only an echo of
        the old default. Those echoes are dropped so they resolve to the new
        value. A sound the user actually chose is left exactly as it is.
        """
        dropped = []
        try:
            from core.sound import SUPERSEDED_DEFAULT_CHOICE
        except Exception:      # noqa: BLE001 — never block start-up
            return dropped
        for event, old in SUPERSEDED_DEFAULT_CHOICE.items():
            key = f"sound_choice_{event}"
            raw = self._qs.value(key, None)
            if raw is not None and str(raw) == old:
                self._qs.remove(key)
                dropped.append(f"{key} ({old} → default)")
        return dropped

    def _migrate_helper_marker_sizes(self) -> list:
        """schema 21 (#152, Knut 2026-08-14): both marker distances become 2.0 mm.

        After seeing them on a real sheet he asked for it plainly: *"change the
        default value for the two spinboxes to 2.0 mm (same for both)"* — in
        place of 1.0 mm from the edge and a 3.0 mm dash.

        Preferences → Save writes every key, so anyone who has ever opened that
        dialog carries a stored copy of the old default that is only an echo of
        it. Those echoes are dropped so they resolve to the new value. A
        distance the user actually set themselves is left exactly as it is —
        which is why each key is checked against its own old default rather than
        cleared outright.
        """
        dropped = []
        for key, old in (("helper_marker_edge_mm", 1.0),
                         ("helper_marker_len_mm", 3.0)):
            raw = self._qs.value(key, None)
            if raw is None:
                continue
            try:
                if abs(float(raw) - old) > 1e-9:
                    continue           # the user's own choice — leave it
            except (TypeError, ValueError):
                continue
            self._qs.remove(key)
            dropped.append(f"{key} ({old} → 2.0)")
        return dropped

    def _migrate_colormunki_min_samples(self) -> bool:
        """schema 14 (#131, Knut 2026-07-27): the ColorMunki's minimum readings
        per patch drops from 30 to 23.

        Knut's practical tests read a strip well at 5-6 seconds where the vendor
        figures imply 7.5, and the profiles came out good — so 30 was holding
        users to a pace the instrument does not actually need. Preferences → Save
        writes every key, so anyone who has ever opened that dialog carries a
        stored 30 that is only an echo of the old default; that echo is dropped
        so it resolves to the new value. A number the user chose themselves is
        left exactly as it is.
        """
        key = "pace_min_samples_colormunki"
        raw = self._qs.value(key, None)
        if raw is None:
            return False
        try:
            if int(float(raw)) != 30:      # the user's own choice — leave it
                return False
        except (TypeError, ValueError):
            return False
        self._qs.remove(key)
        return True

    def _migrate_margin_i1pro_tall_bottom(self) -> bool:
        """schema 12 (#130): raise the i1Pro A4 Portrait / A3 Landscape bottom
        margin to 19 mm so the seeded chart stays under the 240 mm strip-length
        limit. Upgrades a stored ``margin_thresholds`` blob in place, but only for
        combos that still hold the old 9 mm jig default — a customised value is
        left untouched. Fresh installs need nothing (the seed already carries 19)."""
        raw = self._qs.value("margin_thresholds", None)
        if not raw:
            return False
        try:
            table = parse_margin_thresholds(str(raw))
        except Exception:  # noqa: BLE001
            return False
        table, changed = upgrade_margin_i1pro_tall_bottom(table)
        if changed:
            self._qs.setValue("margin_thresholds",
                              serialize_margin_thresholds(table))
        return changed

    def get(self, key: str, default: Any = None) -> Any:
        # On Windows the OS print dialog is the only path that works (no CUPS,
        # no driver-side colour-management toggle we can reach from PostScript).
        # Force the setting True regardless of stored value so a stale False
        # carried over from an older install can't strand the user on the
        # non-functional bypass UI.
        if key == "use_native_print_dialog" and is_windows():
            return True
        fallback = DEFAULTS.get(key, default)
        val = self._qs.value(key, fallback)
        # QSettings can return strings for booleans — coerce
        if isinstance(fallback, bool) and isinstance(val, str):
            val = val.lower() in ("true", "1", "yes")
        elif isinstance(fallback, int) and isinstance(val, str):
            try:
                val = int(val)
            except ValueError:
                val = fallback
        elif isinstance(fallback, float) and isinstance(val, str):
            try:
                val = float(val)
            except ValueError:
                val = fallback
        return val

    def set(self, key: str, value: Any) -> None:
        log.debug("settings.set %s = %r", key, value)
        self._qs.setValue(key, value)

    def sync(self) -> None:
        """Write everything to disk NOW.

        ChromIQ leaves via ``os._exit`` — QtWebEngine and SIP crash if the
        interpreter is allowed to finalize (issue #38) — and ``os._exit`` skips
        every bit of cleanup, including the flush QSettings normally performs
        when it is destroyed or when its timer next fires. So anything written
        during ``closeEvent`` could simply never reach disk, and whichever value
        happened to be flushed once stayed for good.

        That is what made ChromIQ always reopen on the Measure tab whatever tab
        you actually left it on (Knut, #130 2026-07-29). Called at the end of
        ``closeEvent``, while the event loop is still alive, which is the only
        safe moment.
        """
        try:
            self._qs.sync()
        except Exception:      # noqa: BLE001 — never block the app closing
            log.warning("could not flush settings to disk", exc_info=True)

    def reset_to_defaults(self) -> None:
        presets = self._qs.value("manual_presets", "")
        self._qs.clear()
        if presets:
            self._qs.setValue("manual_presets", presets)
        log.info("Settings reset to factory defaults")

    def save_tab_defaults(self, prefix: str, values: dict[str, Any]) -> None:
        """Save a dict of key→value under a given prefix."""
        for k, v in values.items():
            self.set(f"{prefix}_{k}", v)

    # ------------------------------------------------------------------
    # Margin thresholds (JSON blob; see default_margin_thresholds)
    # ------------------------------------------------------------------
    def get_margin_thresholds(self) -> dict[str, dict[str, Any]]:
        """The per-combo margin-threshold table, falling back to the seeds.

        Stored as a JSON string under ``margin_thresholds`` so the whole
        editable matrix round-trips through QSettings as one value.
        """
        return parse_margin_thresholds(self.get("margin_thresholds", ""))

    def set_margin_thresholds(self, table: dict[str, dict[str, Any]]) -> None:
        self.set("margin_thresholds", serialize_margin_thresholds(table))

    # ------------------------------------------------------------------
    # Strip-indicator styling defaults (Knut #93)
    # ------------------------------------------------------------------
    def indicator_style(self) -> dict[str, Any]:
        """The app-wide strip-indicator styling as ``{recipe_field: value}``
        (typed to each DEFAULTS entry)."""
        return {field: self.get(key) for field, key in INDICATOR_STYLE_KEYS.items()}

    def apply_indicator_style(self, recipe):
        """Return *recipe* with its strip-indicator styling fields overlaid from
        the app-wide Settings values. The Settings styling applies to every
        engine chart — recipes from presets or saved defaults carry the fields
        only as inert history (TabChart._current_layout_recipe overlays them)."""
        from dataclasses import replace
        return replace(recipe, **self.indicator_style())
