"""One-time generator: extract CIE reference tables from ArgyllCMS's xspect.c
into ``workflow/cie_data.py``.

The numbers are public-domain CIE colorimetric data (1931 2° observer and the
standard illuminant SPDs) that ArgyllCMS merely redistributes — copying the
tables carries no AGPL obligation (they are data, not Argyll's program code).
We bake them so ChromIQ can recompute XYZ from a measurement's spectral data
under a chosen illuminant without any Argyll call.

Run:  python scripts/gen_cie_data.py /path/to/Argyll/xicc/xspect.c
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

# name in xspect.c -> name in cie_data.py
WANT = {
    "ob_CIE_1931_2": "OBS_1931_2",   # 3 xspects (x,y,z bar)
    "il_A": "IL_A",
    "il_C": "IL_C",
    "il_D50": "IL_D50",
    "il_D65": "IL_D65",
    "il_F5": "IL_F5",
    "il_F8": "IL_F8",
    "il_F10": "IL_F10",
}


def _floats(blob: str) -> list[float]:
    return [float(x) for x in re.findall(r"[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?", blob)]


def _parse_one(src: str, start: int) -> tuple[dict, int]:
    """Parse a single ``{ N, START, END, SCALE, { values } }`` xspect literal
    beginning at the brace index ``start``. Returns (record, index-after)."""
    # header numbers up to the inner '{'
    inner = src.index("{", start + 1)
    n, lo, hi, scale = _floats(src[start + 1:inner])[:4]
    depth = 1
    i = inner + 1
    while depth:
        if src[i] == "{":
            depth += 1
        elif src[i] == "}":
            depth -= 1
        i += 1
    vals = _floats(src[inner + 1:i - 1])
    assert len(vals) == int(n), f"expected {int(n)} got {len(vals)}"
    # advance past this struct's closing brace
    close = src.index("}", i)
    return {"lo": lo, "hi": hi, "n": int(n), "scale": scale, "vals": vals}, close + 1


def parse_array(src: str, cname: str) -> list[dict]:
    m = re.search(rf"static xspect {re.escape(cname)}\s*\[\s*\d+\s*\]\s*=\s*{{", src)
    if not m:
        m = re.search(rf"static xspect {re.escape(cname)}\s*=\s*{{", src)
    assert m, f"{cname} not found"
    # find each inner xspect literal (one for scalar, three for [3])
    i = m.end() - 1  # at the outer '{'
    out = []
    # scalar form: the match already opened the struct brace
    if "[" in src[m.start():m.end()]:
        # array form: iterate sub-structs
        depth = 0
        j = i
        while True:
            nxt = src.find("{", j + 1)
            rec, after = _parse_one(src, nxt)
            out.append(rec)
            if len(out) == 3:
                break
            j = after
    else:
        rec, _ = _parse_one(src, i)
        out.append(rec)
    return out


def main() -> None:
    xspect = Path(sys.argv[1] if len(sys.argv) > 1
                  else "/Users/Basti/Downloads/Argyll_V3.5.0_orig/xicc/xspect.c")
    src = xspect.read_text(encoding="utf-8")
    src = re.sub(r"/\*.*?\*/", " ", src, flags=re.S)   # strip C comments
    src = re.sub(r"//[^\n]*", " ", src)
    lines = ['"""CIE reference tables (generated by scripts/gen_cie_data.py).',
             "",
             "Public-domain CIE 1931 2° observer + standard illuminant SPDs,",
             "extracted from ArgyllCMS xspect.c. Each entry is (lo_nm, hi_nm, [values])",
             "on an even grid of len(values) points; resample with numpy.interp.",
             '"""',
             "from __future__ import annotations", ""]

    obs = parse_array(src, "ob_CIE_1931_2")
    lines.append(f"# 1931 2° observer: {obs[0]['lo']:.0f}-{obs[0]['hi']:.0f} nm,"
                 f" {obs[0]['n']} pts")
    for axis, rec in zip("XYZ", obs):
        lines.append(f"OBS_1931_2_{axis} = ({rec['lo']:.1f}, {rec['hi']:.1f}, [")
        lines += _fmt(rec["vals"])
        lines.append("])")
    lines.append("")
    for cname, pyname in WANT.items():
        if cname == "ob_CIE_1931_2":
            continue
        rec = parse_array(src, cname)[0]
        lines.append(f"{pyname} = ({rec['lo']:.1f}, {rec['hi']:.1f}, [  "
                     f"# {rec['n']} pts")
        lines += _fmt(rec["vals"])
        lines.append("])")
        lines.append("")
    out = Path(__file__).resolve().parent.parent / "workflow" / "cie_data.py"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote", out)


def _fmt(vals: list[float]) -> list[str]:
    rows, row = [], []
    for v in vals:
        row.append(repr(v))
        if len(row) == 8:
            rows.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        rows.append("    " + ", ".join(row) + ",")
    return rows


if __name__ == "__main__":
    main()
