"""Saving an Inspect tool's text into the owner's reports folder (#182).

One door for both Tools ▸ "Inspect a measurement" and "Inspect a profile".
Knut, #182 5943085974 (2026-10-02):

* B1: the saved inspection is named like the Measurement Report's PDF, with
  the time stamp at the end and without its configurable title, so it cannot
  be mistaken for one; no PDF.
* B2: "Inspect a profile" gets its own name in the same style, and *"shall
  also use the reports folder, with the same logic relative to the location of
  the file that were opened for inspection"*.

So the folder is :func:`workflow.run_compliance.reports_dir_for` of the
inspected file: the dated verification's, the run's, the calibration's or the
project's ``reports/``, never ``reads/reports/`` or ``old/<stamp>/reports/``,
and ``<its folder>/reports`` only for a file in no project at all. The folder
is made only for the chooser to open in and removed again unless the file is
saved into it; a same-named file there is archived into ``reports/old/<stamp>/``
before anything is written, and if it cannot be archived nothing is written.
"""
from __future__ import annotations

import os
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Callable, Sequence

from core.i18n import tr
from core.logger import get_logger

log = get_logger(__name__)


@dataclass
class InspectionSave:
    """What a save came to: the file written, or the reason it was not.

    ``path`` None and ``error`` empty is a cancel."""
    path: "Path | None" = None
    error: str = ""


def same_dir(a: Path, b: Path) -> bool:
    """Whether two spellings name one folder (a symlinked temp dir, a
    decomposed name), asked of the disk when both exist."""
    try:
        if a.exists() and b.exists():
            return a.samefile(b)
    except OSError:
        pass
    return Path(a).resolve() == Path(b).resolve()


def _inside_any(folder: Path, roots: "Sequence[Path]") -> bool:
    """Whether *folder* is one of *roots* or lies under one."""
    for r in roots:
        try:
            if folder == Path(r) or Path(r) in folder.parents:
                return True
        except (TypeError, ValueError):
            continue
    return False


def save_inspection(parent, src: Path, kind: str, header_title: str,
                    body_lines: list[str], *, dialog_title: str,
                    subject_line: str,
                    ask: "Callable[..., str] | None" = None,
                    not_into: "Sequence[Path]" = (),
                    fallback_dir: "Path | None" = None) -> InspectionSave:
    """Offer, then write, the inspection of *src*.

    *kind* is the tool's fixed word for its file name ("Measurement
    inspection"), *header_title* the text's own first line, *subject_line*
    the line naming what was inspected, *body_lines* the inspection itself.
    *ask* is the save chooser (``ui.widgets.save_file_dialog`` by default).

    *not_into* names folders no ``reports/`` is ever made in: the system's
    colour-profile folders, which Inspect a profile browses first. A profile
    there lies in no project, so the rule would give
    ``~/Library/ColorSync/Profiles/reports``; the chooser opens in
    *fallback_dir* instead (the user's ChromIQ folder, Preferences > Paths
    first) and nothing is made. A file outside a project in a folder the user
    may not write to (a printer driver's bundle) gets the same fallback.
    """
    from core.version import APP_VERSION
    from workflow.measurement_report import inspection_file_name
    from workflow.run_compliance import in_a_project, reports_dir_for
    if ask is None:
        from ui.widgets import save_file_dialog as ask
    now = datetime.now().replace(microsecond=0)
    header = [
        header_title,
        subject_line,
        tr("Generated by ChromIQ {ver} on {date}").format(
            ver=APP_VERSION, date=now.strftime("%Y-%m-%d %H:%M")),
        "=" * 60,
    ]
    text = "\n".join(header + list(body_lines)) + "\n"
    default = inspection_file_name(kind, src.stem, now)
    reports: "Path | None" = reports_dir_for(src)
    start_dir = src.parent

    def _fallback() -> Path:
        nonlocal fallback_dir
        if fallback_dir is None:
            from core.platform_paths import default_output_root
            fallback_dir = default_output_root()
        return Path(fallback_dir) if Path(fallback_dir).is_dir() else Path.home()

    if _inside_any(reports, not_into):
        start_dir = _fallback()
        reports = None
    elif not in_a_project(src):
        # Outside a ChromIQ project: straight beside the inspected file, and
        # nothing of ours is made there, no reports/ and no old/ archive (Knut,
        # #182 5944210498). A clash is the save dialog's own question.
        reports = None
        # ...unless nobody may write there: a profile inside a printer
        # driver's bundle (/Library/Printers/<maker>/…/Resources, owned by
        # root) would open the chooser in a folder every save fails in. Such
        # a folder is treated like the ColorSync folders above (P-INS-1).
        if not os.access(start_dir, os.W_OK):
            start_dir = _fallback()
    # Made for the chooser to open in (a folder that does not exist is no
    # start folder, `save_file_dialog`), and taken away again unless the file
    # is about to be written into it, as "Save report as PDF…" does (K9): a
    # cancelled save leaves nothing behind.
    made = False
    if reports is not None:
        try:
            if not reports.exists():
                reports.mkdir(parents=True)
                made = True
        except OSError as exc:
            log.warning("could not make %s for the inspection: %s",
                        reports, exc)
        if reports.is_dir():
            start_dir = reports
    # Wherever it came to, a folder nobody may write to is no place to offer
    # (a project on a read-only volume, a printer driver's bundle): the
    # ChromIQ folder instead, as for the ColorSync folders (P-INS-1).
    if not os.access(start_dir, os.W_OK):
        start_dir = _fallback()
    out = ask(parent, dialog_title, tr("Text files (*.txt);;All files (*)"),
              start_path=str(start_dir / default),
              extra_paths=[str(src.parent)])
    if out and not out.lower().endswith(".txt"):
        out += ".txt"
    if made and reports is not None and not (
            out and same_dir(Path(out).parent, reports)):
        try:
            reports.rmdir()          # only ever an empty folder
        except OSError:
            pass
    if not out:
        return InspectionSave()
    target = Path(out)
    # **NEVER OVER A SAVED FILE IN THE REPORTS FOLDER.** A file of the same
    # name there is kept in `reports/old/<stamp>/` first, the archive every
    # rewrite of a report uses; if it cannot be kept, nothing is written. A
    # file chosen anywhere else is the user's own decision, confirmed in the
    # save dialog.
    if (reports is not None and target.is_file()
            and same_dir(target.parent, reports)):
        from core.file_manager import archive_report_files
        try:
            done, _failed = archive_report_files([target], raise_errors=True)
        except OSError as exc:
            return InspectionSave(error=str(exc))
        log.info("kept the earlier %s in %s", target.name,
                 next(iter(done.values()), None))
    try:
        target.write_text(text, encoding="utf-8")
    except OSError as exc:
        return InspectionSave(error=str(exc))
    log.info("inspection saved: %s", target)
    return InspectionSave(path=target)
